/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PharmacyRole;

import ui.SupplierAdminRole.*;
import ui.DoctorRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Hospital.MedicineInventory;
import Business.Hospital.ReplenishmentRequest;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.PharmacyOrganization;
import Business.Organization.ProcurementOrganization;
import Business.Organization.SupplierOrganization;
import Business.Supplier.MaterialInventory;
import Business.Supplier.MaterialRequest;
import Business.Supplier.PickingOrder;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManagePurchaseRequest extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PharmacyOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public ManagePurchaseRequest(JPanel userProcessContainer, UserAccount account, PharmacyOrganization organization, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        
          
        
        populateInventoryTable();
        populateReplenishRequestTable();
    }
    
    public void populateInventoryTable(){
        DefaultTableModel model = (DefaultTableModel) tblInventory.getModel();
        
        model.setRowCount(0);
        
        for (MedicineInventory mi : organization.getMedicineInventoryDirectory().getInventoryList()){
            
                    
            Object[] row = new Object[6];
            row[0] = mi;
            row[1] = mi.getMedicine().getMedicineName();
            row[2] = mi.getQuantity();
            row[3] = mi.getStandardStock();
            row[4] = mi.getShortageQty();
            row[5] = mi.getShortageQty();
            
            
            model.addRow(row);
        }
    }
   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        btnCreatePurchaseOrder = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        enterpriseLabel = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReplenishRequest = new javax.swing.JTable();
        lblPurchaseRequest = new javax.swing.JLabel();
        lblPickingOrder = new javax.swing.JLabel();
        lblReplenish = new javax.swing.JLabel();
        txtReplenishQty = new javax.swing.JTextField();

        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine ID", "Medicine", "Stock Qty", "Standard Qty", "Shortage Qty", "Request Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInventory);
        if (tblInventory.getColumnModel().getColumnCount() > 0) {
            tblInventory.getColumnModel().getColumn(0).setResizable(false);
            tblInventory.getColumnModel().getColumn(1).setResizable(false);
            tblInventory.getColumnModel().getColumn(2).setResizable(false);
            tblInventory.getColumnModel().getColumn(3).setResizable(false);
            tblInventory.getColumnModel().getColumn(4).setResizable(false);
            tblInventory.getColumnModel().getColumn(5).setResizable(false);
        }

        btnCreatePurchaseOrder.setText("Create Replenish Request");
        btnCreatePurchaseOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePurchaseOrderActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        enterpriseLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseLabel.setText("Manage Purchase Request");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblReplenishRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Replenish ID", "Medicine ID", "Medicine", "Request Qty", "Request Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblReplenishRequest);
        if (tblReplenishRequest.getColumnModel().getColumnCount() > 0) {
            tblReplenishRequest.getColumnModel().getColumn(0).setResizable(false);
            tblReplenishRequest.getColumnModel().getColumn(1).setResizable(false);
            tblReplenishRequest.getColumnModel().getColumn(2).setResizable(false);
            tblReplenishRequest.getColumnModel().getColumn(3).setResizable(false);
            tblReplenishRequest.getColumnModel().getColumn(4).setResizable(false);
            tblReplenishRequest.getColumnModel().getColumn(5).setResizable(false);
        }

        lblPurchaseRequest.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblPurchaseRequest.setText("Medicine Inventory");

        lblPickingOrder.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblPickingOrder.setText("Replenish Request");

        lblReplenish.setText("Replenish Qty : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addComponent(lblPurchaseRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnCreatePurchaseOrder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPickingOrder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                                .addGap(58, 58, 58)
                                .addComponent(lblReplenish)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReplenishQty, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 321, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblPurchaseRequest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreatePurchaseOrder)
                    .addComponent(lblReplenish)
                    .addComponent(txtReplenishQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(lblPickingOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnBack)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePurchaseOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePurchaseOrderActionPerformed
        
       int selectedRow = tblInventory.getSelectedRow();
        
        if(selectedRow <0){
            JOptionPane.showMessageDialog(null,"Please select a request","Warning",
    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        MedicineInventory mi = (MedicineInventory) tblInventory.getValueAt(selectedRow,0);
       
        int replenishQty = Integer.valueOf(txtReplenishQty.getText());
        
        ReplenishmentRequest rr = new ReplenishmentRequest();
        rr.setMedicine(mi.getMedicine());
        rr.setReplenishQty(replenishQty);
        rr.setStatus("Requested");
        rr.setSender(userAccount);   // Pharmacy user
        rr.setRequestDate(new Date());
        
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(org instanceof ProcurementOrganization){
                org.getWorkQueue().getWorkRequestList().add(rr);
            }
            
        }
           
        JOptionPane.showMessageDialog(null,"Replenish order has been created");
        
        
    }//GEN-LAST:event_btnCreatePurchaseOrderActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreatePurchaseOrder;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPickingOrder;
    private javax.swing.JLabel lblPurchaseRequest;
    private javax.swing.JLabel lblReplenish;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTable tblReplenishRequest;
    private javax.swing.JTextField txtReplenishQty;
    // End of variables declaration//GEN-END:variables

    private void populateReplenishRequestTable() {
       DefaultTableModel model = (DefaultTableModel) tblReplenishRequest.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()){
            
            if(wr instanceof ReplenishmentRequest){
            
            SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, yyyy");
            ReplenishmentRequest rr = (ReplenishmentRequest)wr;
                     
            Object[] row = new Object[6];
            row[0] = rr;
            row[1] = rr.getMedicine().getMedicineId();
            row[2] = rr.getMedicine().getMedicineName();
            row[3] = rr.getReplenishQty();
            row[4] = sdf.format(rr.getRequestDate());
            row[5] = rr.getStatus();
            
            model.addRow(row);
        }
    }
    
    }
}
