/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PharmacyRole;

import ui.SupplierAdminRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.PharmacyOrganization;
import Business.Organization.SupplierOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ui.SystemAdminWorkArea.ManageEnterpriseJPanel;

/**
 *
 * @author raunak
 */
public class PharmacyWorkAreaPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PharmacyOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public PharmacyWorkAreaPanel(JPanel userProcessContainer, UserAccount account, PharmacyOrganization organization, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
         
        
        enterpriseValueLabel.setText(enterprise.getName());
        userValueLabel.setText(account.getUsername());
    }
    
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCheckInventory = new javax.swing.JButton();
        btnDispensing = new javax.swing.JButton();
        btnReplenishmentRequest = new javax.swing.JButton();
        btnViewOrder = new javax.swing.JButton();
        btnManageUserAccount = new javax.swing.JButton();
        lblEnterprise = new javax.swing.JLabel();
        enterpriseValueLabel = new javax.swing.JLabel();
        userValueLabel = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        enterpriseLabel = new javax.swing.JLabel();

        btnCheckInventory.setBackground(new java.awt.Color(102, 0, 102));
        btnCheckInventory.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnCheckInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckInventory.setText("Check Inventory");
        btnCheckInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInventoryActionPerformed(evt);
            }
        });

        btnDispensing.setBackground(new java.awt.Color(102, 0, 102));
        btnDispensing.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnDispensing.setForeground(new java.awt.Color(255, 255, 255));
        btnDispensing.setText("Dispensing");
        btnDispensing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDispensingActionPerformed(evt);
            }
        });

        btnReplenishmentRequest.setBackground(new java.awt.Color(102, 0, 102));
        btnReplenishmentRequest.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnReplenishmentRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnReplenishmentRequest.setText("Replenishment Request");
        btnReplenishmentRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplenishmentRequestActionPerformed(evt);
            }
        });

        btnViewOrder.setBackground(new java.awt.Color(102, 0, 102));
        btnViewOrder.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnViewOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnViewOrder.setText("View Order Status");
        btnViewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrderActionPerformed(evt);
            }
        });

        btnManageUserAccount.setBackground(new java.awt.Color(102, 0, 102));
        btnManageUserAccount.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnManageUserAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnManageUserAccount.setText("Manage User Account");
        btnManageUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserAccountActionPerformed(evt);
            }
        });

        lblEnterprise.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblEnterprise.setText("Enterprise : ");

        enterpriseValueLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        userValueLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        lblUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblUser.setText("User : ");

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        enterpriseLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseLabel.setText("Pharmacy Portal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDispensing, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReplenishmentRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCheckInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEnterprise, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterpriseValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(130, 130, 130))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEnterprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enterpriseValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser)
                    .addComponent(userValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDispensing, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReplenishmentRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnManageUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInventoryActionPerformed
        // TODO add your handling code here:
        CheckMedicineInventoryPanel cip = new CheckMedicineInventoryPanel(userProcessContainer, organization,enterprise);
        userProcessContainer.add("CheckMedicineInventoryPanel",cip);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCheckInventoryActionPerformed

    private void btnDispensingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDispensingActionPerformed
        // TODO add your handling code here:
        ManageDispensing md = new ManageDispensing(userProcessContainer, userAccount,organization,enterprise);
        userProcessContainer.add("ManageDispensing",md);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
       
        
        
    }//GEN-LAST:event_btnDispensingActionPerformed

    private void btnReplenishmentRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplenishmentRequestActionPerformed
        // TODO add your handling code here:
        ManageReplenishmentRequest mpr = new ManageReplenishmentRequest(userProcessContainer, userAccount,organization,enterprise);
        userProcessContainer.add("ManagePurchaseRequest",mpr);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_btnReplenishmentRequestActionPerformed

    private void btnViewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderActionPerformed
        // TODO add your handling code here:
        ViewPurchaseOrderStatus vpos = new ViewPurchaseOrderStatus(userProcessContainer, userAccount,organization,enterprise);
        userProcessContainer.add("ViewPurchaseOrderStatus",vpos);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
     
    }//GEN-LAST:event_btnViewOrderActionPerformed

    private void btnManageUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserAccountActionPerformed
        // TODO add your handling code here:
        ManagePharmacyUserAccount mua = new ManagePharmacyUserAccount(userProcessContainer, userAccount,organization,enterprise);
        userProcessContainer.add("ManagePharmacyUserAccount",mua);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnManageUserAccountActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckInventory;
    private javax.swing.JButton btnDispensing;
    private javax.swing.JButton btnManageUserAccount;
    private javax.swing.JButton btnReplenishmentRequest;
    private javax.swing.JButton btnViewOrder;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseValueLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel userValueLabel;
    // End of variables declaration//GEN-END:variables
}
