/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.QualityAssuranceRole;

import Business.Organization.Organization;
import Business.Organization.ProductionOrganization;
import Business.Production.FinishedGoods;
import Business.Production.QualityInspectionResult;
import Business.Role.ProductionAdminRole;
import Business.Enterprise.Enterprise;
import Business.Organization.QualityAssuranceOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import ui.ManufacturerShared.OrderStatusJPanel;

/**
 *
 * @author vyngo
 */
public class QualityAssuranceWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form QualityAssuranceWorkAreaJPanel
     */
private JPanel userProcessContainer;
private UserAccount account;
private QualityAssuranceOrganization organization;
private Enterprise enterprise;

public QualityAssuranceWorkAreaJPanel(JPanel userProcessContainer,
                        UserAccount account,
                        QualityAssuranceOrganization organization,
                        Enterprise enterprise) {
    initComponents();
    this.userProcessContainer = userProcessContainer;
    this.account = account;
    this.organization = organization;
    this.enterprise = enterprise;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        receiveFinishedGoodsButton = new javax.swing.JButton();
        executeQualityInspectionButton = new javax.swing.JButton();
        enterInspectionResultButton = new javax.swing.JButton();
        viewOrderStatusButton = new javax.swing.JButton();
        myProfileButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();

        receiveFinishedGoodsButton.setText("Receive Finished Goods");
        receiveFinishedGoodsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveFinishedGoodsButtonActionPerformed(evt);
            }
        });

        executeQualityInspectionButton.setText("Execute Quality Inspection");
        executeQualityInspectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeQualityInspectionButtonActionPerformed(evt);
            }
        });

        enterInspectionResultButton.setText("Enter Quality Inspection Result");
        enterInspectionResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterInspectionResultButtonActionPerformed(evt);
            }
        });

        viewOrderStatusButton.setText("View Order Status");
        viewOrderStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderStatusButtonActionPerformed(evt);
            }
        });

        myProfileButton.setText("My Profile");
        myProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myProfileButtonActionPerformed(evt);
            }
        });

        titleLabel.setText("Quality Assurance Portal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(executeQualityInspectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(receiveFinishedGoodsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewOrderStatusButton, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(myProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(enterInspectionResultButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiveFinishedGoodsButton)
                    .addComponent(viewOrderStatusButton))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executeQualityInspectionButton)
                    .addComponent(myProfileButton))
                .addGap(30, 30, 30)
                .addComponent(enterInspectionResultButton)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void receiveFinishedGoodsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveFinishedGoodsButtonActionPerformed
        // TODO add your handling code here:
    java.util.ArrayList<FinishedGoods> pending = new java.util.ArrayList<>();
    for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
        if (wr instanceof FinishedGoods && wr.getReceiver() == account && "Sent".equals(wr.getStatus())) {
            pending.add((FinishedGoods) wr);
        }
    }
    if (pending.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No finished goods pending receipt.");
        return;
    }

    String[] labels = new String[pending.size()];
    for (int i = 0; i < pending.size(); i++) {
        FinishedGoods fg = pending.get(i);
        labels[i] = fg.getProductName() + " x " + fg.getQty() + " (Plan " + fg.getPlanId() + ")";
    }
    String selected = (String) javax.swing.JOptionPane.showInputDialog(
            this,
            "Select finished goods to receive:",
            "Receive Finished Goods",
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            labels,
            labels[0]);
    if (selected == null) {
        return;
    }
    int selectedIndex = java.util.Arrays.asList(labels).indexOf(selected);
    FinishedGoods fg = pending.get(selectedIndex);

    fg.setStatus("Received");

    javax.swing.JOptionPane.showMessageDialog(this, "Received " + fg.getProductName() + " x " + fg.getQty()
            + " (Plan " + fg.getPlanId() + "). You can now execute the quality inspection.");
    }//GEN-LAST:event_receiveFinishedGoodsButtonActionPerformed

    private void executeQualityInspectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeQualityInspectionButtonActionPerformed
        // TODO add your handling code here:
    java.util.ArrayList<FinishedGoods> received = new java.util.ArrayList<>();
    for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
        if (wr instanceof FinishedGoods && wr.getReceiver() == account && "Received".equals(wr.getStatus())) {
            received.add((FinishedGoods) wr);
        }
    }
    if (received.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No received finished goods to inspect. Please receive finished goods first.");
        return;
    }

    String[] labels = new String[received.size()];
    for (int i = 0; i < received.size(); i++) {
        FinishedGoods fg = received.get(i);
        labels[i] = fg.getProductName() + " x " + fg.getQty() + " (Plan " + fg.getPlanId() + ")";
    }
    String selected = (String) javax.swing.JOptionPane.showInputDialog(
            this,
            "Select finished goods to inspect:",
            "Execute Quality Inspection",
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            labels,
            labels[0]);
    if (selected == null) {
        return;
    }
    int selectedIndex = java.util.Arrays.asList(labels).indexOf(selected);
    FinishedGoods fg = received.get(selectedIndex);

    fg.setStatus("Inspected");

    javax.swing.JOptionPane.showMessageDialog(this, "Quality inspection executed for " + fg.getProductName() + " x " + fg.getQty()
            + " (Plan " + fg.getPlanId() + "). You can now enter the inspection result.");
    }//GEN-LAST:event_executeQualityInspectionButtonActionPerformed

    private void enterInspectionResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterInspectionResultButtonActionPerformed
        // TODO add your handling code here:
    java.util.ArrayList<FinishedGoods> inspected = new java.util.ArrayList<>();
    for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
        if (wr instanceof FinishedGoods && wr.getReceiver() == account && "Inspected".equals(wr.getStatus())) {
            inspected.add((FinishedGoods) wr);
        }
    }
    if (inspected.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No inspected finished goods to submit a result for. Please execute quality inspection first.");
        return;
    }

    String[] labels = new String[inspected.size()];
    for (int i = 0; i < inspected.size(); i++) {
        FinishedGoods fg = inspected.get(i);
        labels[i] = fg.getProductName() + " x " + fg.getQty() + " (Plan " + fg.getPlanId() + ")";
    }
    String selected = (String) javax.swing.JOptionPane.showInputDialog(
            this,
            "Select inspected finished goods:",
            "Enter Quality Inspection Result",
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            labels,
            labels[0]);
    if (selected == null) {
        return;
    }
    int selectedIndex = java.util.Arrays.asList(labels).indexOf(selected);
    FinishedGoods fg = inspected.get(selectedIndex);

    int response = javax.swing.JOptionPane.showConfirmDialog(this, "Did " + fg.getProductName() + " pass inspection?", "Quality Inspection Result", javax.swing.JOptionPane.YES_NO_OPTION);
    boolean passed = (response == javax.swing.JOptionPane.YES_OPTION);

    String failureReason = null;
    if (!passed) {
        failureReason = javax.swing.JOptionPane.showInputDialog(this, "Reason for failure:", "Quality Inspection Result", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (failureReason == null || failureReason.trim().isEmpty()) {
            failureReason = "No reason provided";
        }
    }

    ProductionOrganization productionOrg = null;
    for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
        if (org instanceof ProductionOrganization) {
            productionOrg = (ProductionOrganization) org;
            break;
        }
    }
    if (productionOrg == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No Production organization found.");
        return;
    }

    java.util.ArrayList<UserAccount> adminAccounts = new java.util.ArrayList<>();
    for (UserAccount ua : productionOrg.getUserAccountDirectory().getUserAccountList()) {
        if (ua.getRole() instanceof ProductionAdminRole) {
            adminAccounts.add(ua);
        }
    }
    if (adminAccounts.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No Production Admin account found.");
        return;
    }
    UserAccount adminAccount;
    if (adminAccounts.size() == 1) {
        adminAccount = adminAccounts.get(0);
    } else {
        String[] adminNames = new String[adminAccounts.size()];
        for (int i = 0; i < adminAccounts.size(); i++) {
            adminNames[i] = adminAccounts.get(i).getUsername();
        }
        String selectedAdminName = (String) javax.swing.JOptionPane.showInputDialog(
                this,
                "Select Production Admin to notify:",
                "Enter Quality Inspection Result",
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                adminNames,
                adminNames[0]);
        if (selectedAdminName == null) {
            return;
        }
        adminAccount = null;
        for (UserAccount ua : adminAccounts) {
            if (ua.getUsername().equals(selectedAdminName)) {
                adminAccount = ua;
                break;
            }
        }
    }

    QualityInspectionResult result = new QualityInspectionResult(fg.getProductName(), passed);
    result.setPlanId(fg.getPlanId());
    result.setMessage("Inspection result for " + fg.getProductName() + ": " + (passed ? "Passed" : "Failed"
            + " - Reason: " + failureReason));
    result.setSender(account);
    result.setReceiver(adminAccount);
    productionOrg.getWorkQueue().getWorkRequestList().add(result);
    // Also keep a reference in QA's own queue (same object) so this result
    // shows up under QA's own "View Order Status" too.
    organization.getWorkQueue().getWorkRequestList().add(result);

    fg.setStatus("Closed");
    fg.setResolveDate(new java.util.Date());

    javax.swing.JOptionPane.showMessageDialog(this, "Inspection result submitted for " + fg.getProductName()
            + " (Plan " + fg.getPlanId() + "): " + (passed ? "Passed" : "Failed"));

    }//GEN-LAST:event_enterInspectionResultButtonActionPerformed

    private void viewOrderStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderStatusButtonActionPerformed
        // TODO add your handling code here:
    OrderStatusJPanel p = new OrderStatusJPanel(userProcessContainer, organization);
    userProcessContainer.add("OrderStatusJPanel", p);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);

    }//GEN-LAST:event_viewOrderStatusButtonActionPerformed

    private void myProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myProfileButtonActionPerformed
        // TODO add your handling code here:
        String employeeName = account.getEmployee() == null ? "N/A" : account.getEmployee().getName();
        String roleName = account.getRole() == null ? "N/A" : account.getRole().toString();
        String profile = "Username: " + account.getUsername()
                + "\nEmployee Name: " + employeeName
                + "\nRole: " + roleName
                + "\nOrganization: " + organization.getClass().getSimpleName();
        javax.swing.JOptionPane.showMessageDialog(this, profile, "My Profile", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_myProfileButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterInspectionResultButton;
    private javax.swing.JButton executeQualityInspectionButton;
    private javax.swing.JButton myProfileButton;
    private javax.swing.JButton receiveFinishedGoodsButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewOrderStatusButton;
    // End of variables declaration//GEN-END:variables
}
