/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.MaterialShippingRole;

import ui.SupplierAdminRole.*;
import ui.DoctorRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.SupplierOrganization;
import Business.Supplier.MaterialInventory;
import Business.Supplier.MaterialRequest;
import Business.Supplier.PickingOrder;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManageShippingRequest extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private SupplierOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public ManageShippingRequest(JPanel userProcessContainer, UserAccount account, SupplierOrganization organization, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        
        tblShippingOrder.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
        tblShippingOrder.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        
        
        populateShippingOrderTable();
        populatePickingOrderTable();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblShippingOrder = new javax.swing.JTable();
        btnLoadingComplete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        enterpriseLabel = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPickingOrder = new javax.swing.JTable();
        lblMaterialRequest = new javax.swing.JLabel();
        lblPickingOrder = new javax.swing.JLabel();
        btnPrintPickingList = new javax.swing.JButton();
        btnCompletePicking = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblShippingOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Material ID", "Material", "Request Qty", "Available Qty", "Picking Qty", "Request Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblShippingOrder);
        if (tblShippingOrder.getColumnModel().getColumnCount() > 0) {
            tblShippingOrder.getColumnModel().getColumn(0).setResizable(false);
            tblShippingOrder.getColumnModel().getColumn(1).setResizable(false);
            tblShippingOrder.getColumnModel().getColumn(2).setResizable(false);
            tblShippingOrder.getColumnModel().getColumn(2).setHeaderValue("Request Qty");
            tblShippingOrder.getColumnModel().getColumn(3).setResizable(false);
            tblShippingOrder.getColumnModel().getColumn(3).setHeaderValue("Available Qty");
            tblShippingOrder.getColumnModel().getColumn(4).setResizable(false);
            tblShippingOrder.getColumnModel().getColumn(5).setResizable(false);
            tblShippingOrder.getColumnModel().getColumn(6).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 770, 160));

        btnLoadingComplete.setText("Loading Complete");
        btnLoadingComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadingCompleteActionPerformed(evt);
            }
        });
        add(btnLoadingComplete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 166, -1));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        enterpriseLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseLabel.setText("Manage Material Request");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        tblPickingOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Picking Order ID", "Material ID", "Material", "Request Qty", "Picking Qty", "Request Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPickingOrder);
        if (tblPickingOrder.getColumnModel().getColumnCount() > 0) {
            tblPickingOrder.getColumnModel().getColumn(0).setResizable(false);
            tblPickingOrder.getColumnModel().getColumn(1).setResizable(false);
            tblPickingOrder.getColumnModel().getColumn(2).setResizable(false);
            tblPickingOrder.getColumnModel().getColumn(3).setResizable(false);
            tblPickingOrder.getColumnModel().getColumn(4).setResizable(false);
            tblPickingOrder.getColumnModel().getColumn(5).setResizable(false);
            tblPickingOrder.getColumnModel().getColumn(6).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 776, 130));

        lblMaterialRequest.setText("Shipping Order");
        add(lblMaterialRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        lblPickingOrder.setText("Picking Order");
        add(lblPickingOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        btnPrintPickingList.setText("Print Picking List");
        btnPrintPickingList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintPickingListActionPerformed(evt);
            }
        });
        add(btnPrintPickingList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 166, -1));

        btnCompletePicking.setText("Picking complete");
        btnCompletePicking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletePickingActionPerformed(evt);
            }
        });
        add(btnCompletePicking, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 166, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadingCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadingCompleteActionPerformed
          int selectedRow = tblShippingOrder.getSelectedRow();
        
        if(selectedRow <0){
            JOptionPane.showMessageDialog(null,"Please select an order","Warning",
    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        PickingOrder po = (PickingOrder) tblShippingOrder.getValueAt(selectedRow,0);
        
        if (po.getStatus().equals("Picked")) {

        int option = JOptionPane.showConfirmDialog(
            null,
            "Are you sure you want to complete loading?",
            "Confirmation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (option != JOptionPane.YES_OPTION) {
            return;
        }

        po.setStatus("Loaded");

        } else {

        JOptionPane.showMessageDialog(
            null,
            "The order has been loaded.",
            "Warning",
            JOptionPane.WARNING_MESSAGE);

        return;
        }
        
        populateShippingOrderTable();
     
        
    }//GEN-LAST:event_btnLoadingCompleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPrintPickingListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintPickingListActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPickingOrder.getSelectedRow();
        
        if(selectedRow <0){
            JOptionPane.showMessageDialog(null,"Please select an order","Warning",
    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        PickingOrder po = (PickingOrder) tblPickingOrder.getValueAt(selectedRow,0);
        
        if (po.getStatus().equals("Allocated")) {

        int option = JOptionPane.showConfirmDialog(
            null,
            "Are you sure you want to start picking?",
            "Confirmation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (option != JOptionPane.YES_OPTION) {
            return;
        }

        po.setStatus("Picking");

        } else {

        JOptionPane.showMessageDialog(
            null,
            "The picking list can only be printed for orders with 'Allocated' status.",
            "Warning",
            JOptionPane.WARNING_MESSAGE);

        return;
        }
        
        populatePickingOrderTable();
        
    }//GEN-LAST:event_btnPrintPickingListActionPerformed

    private void btnCompletePickingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletePickingActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblPickingOrder.getSelectedRow();
        
        if(selectedRow <0){
            JOptionPane.showMessageDialog(null,"Please select an order","Warning",
    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        PickingOrder po = (PickingOrder) tblPickingOrder.getValueAt(selectedRow,0);
        
        if (po.getStatus().equals("Picking")) {

        int option = JOptionPane.showConfirmDialog(
            null,
            "Are you sure you want to complete picking?",
            "Confirmation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (option != JOptionPane.YES_OPTION) {
            return;
        }

        po.setStatus("Picked");

        } else {

        JOptionPane.showMessageDialog(
            null,
            "Picking can not be completed.",
            "Warning",
            JOptionPane.WARNING_MESSAGE);

        return;
        }
        
        populatePickingOrderTable();
        populateShippingOrderTable();
        
    }//GEN-LAST:event_btnCompletePickingActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCompletePicking;
    private javax.swing.JButton btnLoadingComplete;
    private javax.swing.JButton btnPrintPickingList;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMaterialRequest;
    private javax.swing.JLabel lblPickingOrder;
    private javax.swing.JTable tblPickingOrder;
    private javax.swing.JTable tblShippingOrder;
    // End of variables declaration//GEN-END:variables

    private void populatePickingOrderTable() {
       DefaultTableModel model = (DefaultTableModel) tblPickingOrder.getModel();
        
        model.setRowCount(0);
        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()){
            
            if(wr instanceof PickingOrder){
            
            SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, yyyy");
            PickingOrder po = (PickingOrder)wr;
            
            if (po.getStatus().equals("Allocated")||po.getStatus().equals("Picking")) {
            
            Object[] row = new Object[7];
            row[0] = po;
            row[1] = po.getMaterialRequest().getMaterial();
            row[2] = po.getMaterialRequest().getMaterial().getMaterialName();
            row[3] = po.getMaterialRequest().getQty();
            row[4] = po.getMaterialRequest().getQty();
            row[5] = sdf.format(po.getRequestDate());
            row[6] = po.getStatus();
            
            model.addRow(row);
            }
        }
    }
    
    }
    
     public void populateShippingOrderTable(){
        DefaultTableModel model = (DefaultTableModel) tblShippingOrder.getModel();
        
        model.setRowCount(0);
        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()){
            
            if(wr instanceof PickingOrder){
            
            SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, yyyy");
            PickingOrder po = (PickingOrder)wr;
            
            if (po.getStatus().equals("Picked")||po.getStatus().equals("Loaded")) {
            
            Object[] row = new Object[7];
            row[0] = po;
            row[1] = po.getMaterialRequest().getMaterial();
            row[2] = po.getMaterialRequest().getMaterial().getMaterialName();
            row[3] = po.getMaterialRequest().getQty();
            row[4] = po.getMaterialRequest().getQty();
            row[5] = sdf.format(po.getRequestDate());
            row[6] = po.getStatus();
            
            model.addRow(row);
        }
    }
    }
    
     }

}
