/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ProductionRole;

import Business.Organization.Organization;
import Business.Organization.QualityAssuranceOrganization;
import Business.Production.FinishedGoods;
import Business.Role.QualityAssuranceRole;
import Business.Enterprise.Enterprise;
import Business.Organization.ProductionOrganization;
import Business.UserAccount.UserAccount;
import Business.Supplier.Material;
import Business.Supplier.MaterialInventory;
import Business.Supplier.MaterialRequest;
import Business.Production.ProductionOrder;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;

/**
 *
 * @author vyngo
 */
public class ProductionWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductionWorkAreaJPanel
     */
private JPanel userProcessContainer;
private UserAccount account;
private ProductionOrganization organization;
private Enterprise enterprise;

public ProductionWorkAreaJPanel(JPanel userProcessContainer,
                        UserAccount account,
                        ProductionOrganization organization,
                        Enterprise enterprise) {
    initComponents();
    this.userProcessContainer = userProcessContainer;
    this.account = account;
    this.organization = organization;
    this.enterprise = enterprise;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        receiveRawMaterialsButton = new javax.swing.JButton();
        registerFinishedGoodsButton = new javax.swing.JButton();
        myProfileButton = new javax.swing.JButton();
        executeProductionButton = new javax.swing.JButton();
        shippingButton = new javax.swing.JButton();
        viewOrderStatusButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();

        receiveRawMaterialsButton.setText("Receive Raw Materials");
        receiveRawMaterialsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveRawMaterialsButtonActionPerformed(evt);
            }
        });

        registerFinishedGoodsButton.setText("Register Finished Goods");
        registerFinishedGoodsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerFinishedGoodsButtonActionPerformed(evt);
            }
        });

        myProfileButton.setText("My Profile");
        myProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myProfileButtonActionPerformed(evt);
            }
        });

        executeProductionButton.setText("Execute Production");
        executeProductionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeProductionButtonActionPerformed(evt);
            }
        });

        shippingButton.setText("Shipping");
        shippingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shippingButtonActionPerformed(evt);
            }
        });

        viewOrderStatusButton.setText("View Order Status");
        viewOrderStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderStatusButtonActionPerformed(evt);
            }
        });

        titleLabel.setText("Production Operator Portal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(receiveRawMaterialsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerFinishedGoodsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(myProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shippingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(executeProductionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(viewOrderStatusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(223, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiveRawMaterialsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(executeProductionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(registerFinishedGoodsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(myProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(shippingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewOrderStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void receiveRawMaterialsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveRawMaterialsButtonActionPerformed
        // TODO add your handling code here:
    java.util.ArrayList<MaterialRequest> pending = new java.util.ArrayList<>();
    for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
        if (wr instanceof MaterialRequest && !"Received".equals(wr.getStatus())) {
            pending.add((MaterialRequest) wr);
        }
    }
    if (pending.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No pending material request to receive.");
        return;
    }

    String[] labels = new String[pending.size()];
    for (int i = 0; i < pending.size(); i++) {
        MaterialRequest mr = pending.get(i);
        labels[i] = mr.getMaterial().getMaterialName() + " x " + mr.getQty() + " (" + mr.getStatus() + ")";
    }
    String selected = (String) javax.swing.JOptionPane.showInputDialog(
            this,
            "Select material request to receive:",
            "Receive Raw Materials",
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            labels,
            labels[0]);
    if (selected == null) {
        return;
    }
    int selectedIndex = java.util.Arrays.asList(labels).indexOf(selected);
    MaterialRequest mr = pending.get(selectedIndex);

    Material material = mr.getMaterial();
    MaterialInventory inventory = organization.getRawMaterialInventoryDirectory().findInventoryByMaterial(material);
    if (inventory == null) {
        organization.getRawMaterialInventoryDirectory().addInventory(material, mr.getQty());
    } else {
        inventory.setAvailableQty(inventory.getAvailableQty() + mr.getQty());
    }

    mr.setStatus("Received");
    mr.setResolveDate(new java.util.Date());

    javax.swing.JOptionPane.showMessageDialog(this, "Received " + mr.getQty() + " x " + material.getMaterialName() + " into raw material stock.");
    }//GEN-LAST:event_receiveRawMaterialsButtonActionPerformed

    private void executeProductionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeProductionButtonActionPerformed
        // TODO add your handling code here:
    java.util.ArrayList<ProductionOrder> pending = new java.util.ArrayList<>();
    for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
        if (wr instanceof ProductionOrder && wr.getReceiver() == account && "Sent".equals(wr.getStatus())) {
            pending.add((ProductionOrder) wr);
        }
    }
    if (pending.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No pending production order to execute.");
        return;
    }

    String[] labels = new String[pending.size()];
    for (int i = 0; i < pending.size(); i++) {
        ProductionOrder po = pending.get(i);
        labels[i] = po.getProductName() + " x " + po.getQty() + " (Plan " + po.getPlanId() + ")";
    }
    String selected = (String) javax.swing.JOptionPane.showInputDialog(
            this,
            "Select production order to execute:",
            "Execute Production",
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            labels,
            labels[0]);
    if (selected == null) {
        return;
    }
    int selectedIndex = java.util.Arrays.asList(labels).indexOf(selected);
    ProductionOrder po = pending.get(selectedIndex);

    java.util.ArrayList<MaterialInventory> stock = organization.getRawMaterialInventoryDirectory().getInventoryList();
    if (stock.isEmpty()) {
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Raw material stock is currently empty. Execute this production order anyway?",
                "Low Stock Warning",
                javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }
    }

    po.setStatus("Completed");
    po.setResolveDate(new java.util.Date());

    javax.swing.JOptionPane.showMessageDialog(this, "Production executed for " + po.getProductName()
            + " x " + po.getQty() + ". You can now register the finished goods.");
    }//GEN-LAST:event_executeProductionButtonActionPerformed

    private void registerFinishedGoodsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerFinishedGoodsButtonActionPerformed
        // TODO add your handling code here:
    java.util.ArrayList<ProductionOrder> completedOrders = new java.util.ArrayList<>();
    for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
        if (wr instanceof ProductionOrder && wr.getReceiver() == account && "Completed".equals(wr.getStatus())) {
            completedOrders.add((ProductionOrder) wr);
        }
    }
    if (completedOrders.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No completed production order to register. Please execute a production order first.");
        return;
    }

    String[] labels = new String[completedOrders.size()];
    for (int i = 0; i < completedOrders.size(); i++) {
        ProductionOrder po = completedOrders.get(i);
        labels[i] = po.getProductName() + " x " + po.getQty() + " (Plan " + po.getPlanId() + ")";
    }
    String selected = (String) javax.swing.JOptionPane.showInputDialog(
            this,
            "Select completed production order to register:",
            "Register Finished Goods",
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            labels,
            labels[0]);
    if (selected == null) {
        return;
    }
    int selectedIndex = java.util.Arrays.asList(labels).indexOf(selected);
    ProductionOrder po = completedOrders.get(selectedIndex);

    String qtyStr = (String) javax.swing.JOptionPane.showInputDialog(
            this,
            "Enter actual finished quantity:",
            "Register Finished Goods",
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            null,
            String.valueOf(po.getQty()));
    if (qtyStr == null || qtyStr.trim().isEmpty()) {
        return;
    }
    int qty;
    try {
        qty = Integer.parseInt(qtyStr.trim());
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Quantity must be a number.");
        return;
    }
    if (qty <= 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Quantity must be greater than 0.");
        return;
    }

    QualityAssuranceOrganization qaOrg = null;
    for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
        if (org instanceof QualityAssuranceOrganization) {
            qaOrg = (QualityAssuranceOrganization) org;
            break;
        }
    }
    if (qaOrg == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No Quality Assurance organization found.");
        return;
    }

    java.util.ArrayList<UserAccount> qaAccounts = new java.util.ArrayList<>();
    for (UserAccount ua : qaOrg.getUserAccountDirectory().getUserAccountList()) {
        if (ua.getRole() instanceof QualityAssuranceRole) {
            qaAccounts.add(ua);
        }
    }
    if (qaAccounts.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No Quality Assurance account found.");
        return;
    }
    UserAccount qaAccount;
    if (qaAccounts.size() == 1) {
        qaAccount = qaAccounts.get(0);
    } else {
        String[] qaNames = new String[qaAccounts.size()];
        for (int i = 0; i < qaAccounts.size(); i++) {
            qaNames[i] = qaAccounts.get(i).getUsername();
        }
        String selectedQaName = (String) javax.swing.JOptionPane.showInputDialog(
                this,
                "Select Quality Assurance reviewer:",
                "Register Finished Goods",
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                qaNames,
                qaNames[0]);
        if (selectedQaName == null) {
            return;
        }
        qaAccount = null;
        for (UserAccount ua : qaAccounts) {
            if (ua.getUsername().equals(selectedQaName)) {
                qaAccount = ua;
                break;
            }
        }
    }

    FinishedGoods fg = new FinishedGoods(po.getProductName(), qty);
    fg.setPlanId(po.getPlanId());
    fg.setMessage("Finished goods ready for inspection: " + po.getProductName());
    fg.setSender(account);
    fg.setReceiver(qaAccount);
    qaOrg.getWorkQueue().getWorkRequestList().add(fg);
    // Also keep a reference in Production's own queue (same object) so this
    // hand-off shows up under Production Admin's "View Order Status" too.
    organization.getWorkQueue().getWorkRequestList().add(fg);

    po.setStatus("Registered");

    javax.swing.JOptionPane.showMessageDialog(this, "Finished goods registered and sent to QA: " + po.getProductName()
            + " x " + qty + " (Plan " + po.getPlanId() + ")");

    }//GEN-LAST:event_registerFinishedGoodsButtonActionPerformed

    private void shippingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shippingButtonActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "TODO: Shipping screen");
    }//GEN-LAST:event_shippingButtonActionPerformed

    private void myProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myProfileButtonActionPerformed
        // TODO add your handling code here:
         javax.swing.JOptionPane.showMessageDialog(this, "TODO: My Profile screen");
    }//GEN-LAST:event_myProfileButtonActionPerformed

    private void viewOrderStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderStatusButtonActionPerformed
        // TODO add your handling code here:
    java.util.ArrayList<WorkRequest> requests = organization.getWorkQueue().getWorkRequestList();
    if (requests.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No requests in the queue.");
        return;
    }
    StringBuilder sb = new StringBuilder();
    for (WorkRequest wr : requests) {
        sb.append(wr.toString()).append(" - ").append(wr.getStatus()).append("\n");
    }
    javax.swing.JOptionPane.showMessageDialog(this, sb.toString(), "Order Status", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_viewOrderStatusButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton executeProductionButton;
    private javax.swing.JButton myProfileButton;
    private javax.swing.JButton receiveRawMaterialsButton;
    private javax.swing.JButton registerFinishedGoodsButton;
    private javax.swing.JButton shippingButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewOrderStatusButton;
    // End of variables declaration//GEN-END:variables
}
