/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TransportRole;

import Business.Organization.TransportOrganization;
import Business.Role.DriverRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DeliveryWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class CreateDeliveryOrderJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final TransportOrganization organization;
    private final UserAccount admin;

    public CreateDeliveryOrderJPanel(JPanel userProcessContainer,
            TransportOrganization organization, UserAccount admin) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.admin = admin;
        populateTable();
        populateDrivers();
    }

    public void populateTable() {
        DefaultTableModel m = (DefaultTableModel) requestJTable.getModel();
        m.setRowCount(0);
        for (WorkRequest r : organization.getWorkQueue().getWorkRequestList()) {
            if (!(r instanceof DeliveryWorkRequest)) continue;
            DeliveryWorkRequest d = (DeliveryWorkRequest) r;
            if (!DeliveryWorkRequest.STATUS_ASSIGNED.equals(d.getStatus())) continue;
            m.addRow(new Object[]{d, d.getPickupLocation(), d.getDropLocation(),
                d.getAssignedTruck(), d.getStatus()});
        }
    }

    private void populateDrivers() {
        driverJComboBox.removeAllItems();
        for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
            if (ua.getRole() instanceof DriverRole) driverJComboBox.addItem(ua);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        driverJComboBox = new javax.swing.JComboBox<>();
        backJButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestJTable = new javax.swing.JTable();
        dispatchJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        driverLabel = new javax.swing.JLabel();

        driverJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverJComboBoxActionPerformed(evt);
            }
        });

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setText("Create Delivery Order");

        requestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request", "Pickup", "Drop", "Truck", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestJTable);

        dispatchJButton.setText("Dispatch");
        dispatchJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispatchJButtonActionPerformed(evt);
            }
        });

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        driverLabel.setText("Driver:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(driverLabel)
                        .addGap(18, 18, 18)
                        .addComponent(driverJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(dispatchJButton)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backJButton)
                            .addComponent(refreshJButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(driverJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dispatchJButton)
                    .addComponent(refreshJButton)
                    .addComponent(driverLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(backJButton)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void driverJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverJComboBoxActionPerformed

    private void dispatchJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispatchJButtonActionPerformed
        // TODO add your handling code here:
        int row = requestJTable.getSelectedRow();
        if (row < 0) { JOptionPane.showMessageDialog(this, "Pick a request."); return; }
        UserAccount driver = (UserAccount) driverJComboBox.getSelectedItem();
        if (driver == null) { JOptionPane.showMessageDialog(this, "No driver selected."); return; }
        DeliveryWorkRequest d = (DeliveryWorkRequest) requestJTable.getValueAt(row, 0);
        d.setAssignedDriver(driver);
        d.setReceiver(driver);
        if (!driver.getWorkQueue().getWorkRequestList().contains(d)) {
            driver.getWorkQueue().getWorkRequestList().add(d);
        }
        JOptionPane.showMessageDialog(this, "Dispatched to " + driver.getUsername());
        populateTable();
    }//GEN-LAST:event_dispatchJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        populateTable(); 
        populateDrivers();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton dispatchJButton;
    private javax.swing.JComboBox<UserAccount> driverJComboBox;
    private javax.swing.JLabel driverLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTable requestJTable;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
