/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TransportRole;

import Business.Organization.TransportOrganization;
import Business.Role.DriverRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DeliveryWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class CreateDeliveryOrderJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final TransportOrganization organization;
    private final UserAccount admin;

    public CreateDeliveryOrderJPanel(JPanel userProcessContainer,
            TransportOrganization organization, UserAccount admin) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.admin = admin;
        populateTable();
        populateDrivers();
    }

    public void populateTable() {
        DefaultTableModel m = (DefaultTableModel) requestJTable.getModel();
        m.setRowCount(0);
        for (WorkRequest r : organization.getWorkQueue().getWorkRequestList()) {
            if (!(r instanceof DeliveryWorkRequest)) continue;
            DeliveryWorkRequest d = (DeliveryWorkRequest) r;
            if (!DeliveryWorkRequest.STATUS_ASSIGNED.equals(d.getStatus())) continue;
            m.addRow(new Object[]{d, d.getPickupLocation(), d.getDropLocation(),
                d.getAssignedTruck(), d.getStatus()});
        }
        autoSizeColumns(requestJTable);
    }
    
    private void autoSizeColumns(javax.swing.JTable t) {
        t.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        for (int col = 0; col < t.getColumnCount(); col++) {
            int w = 60;
            for (int r = 0; r < t.getRowCount(); r++) {
                w = Math.max(w, t.prepareRenderer(t.getCellRenderer(r, col), r, col)
                               .getPreferredSize().width + 20);
            }
            t.getColumnModel().getColumn(col).setPreferredWidth(w);
        }
    }

    private void populateDrivers() {
        driverJComboBox.removeAllItems();
        for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
            if (ua.getRole() instanceof DriverRole) driverJComboBox.addItem(ua);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        driverJComboBox = new javax.swing.JComboBox<>();
        backJButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestJTable = new javax.swing.JTable();
        dispatchJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        driverLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        driverJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverJComboBoxActionPerformed(evt);
            }
        });
        add(driverJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 194, 97, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 271, -1, -1));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setText("Create Delivery Order");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 27, -1, -1));

        requestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request", "Pickup", "Drop", "Truck", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 71, 538, 105));

        dispatchJButton.setText("Dispatch");
        dispatchJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispatchJButtonActionPerformed(evt);
            }
        });
        add(dispatchJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 194, -1, -1));

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 194, -1, -1));

        driverLabel.setText("Driver:");
        add(driverLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 197, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void driverJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverJComboBoxActionPerformed

    private void dispatchJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispatchJButtonActionPerformed
        // TODO add your handling code here:
        int row = requestJTable.getSelectedRow();
        if (row < 0) { JOptionPane.showMessageDialog(this, "Pick a request."); return; }
        UserAccount driver = (UserAccount) driverJComboBox.getSelectedItem();
        if (driver == null) { JOptionPane.showMessageDialog(this, "No driver selected."); return; }
        DeliveryWorkRequest d = (DeliveryWorkRequest) requestJTable.getValueAt(row, 0);
        d.setAssignedDriver(driver);
        d.setReceiver(driver);
        if (!driver.getWorkQueue().getWorkRequestList().contains(d)) {
            driver.getWorkQueue().getWorkRequestList().add(d);
        }
        JOptionPane.showMessageDialog(this, "Dispatched to " + driver.getUsername());
        populateTable();
    }//GEN-LAST:event_dispatchJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        populateTable(); 
        populateDrivers();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton dispatchJButton;
    private javax.swing.JComboBox<UserAccount> driverJComboBox;
    private javax.swing.JLabel driverLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTable requestJTable;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
