/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TransportRole;

import Business.Enterprise.Enterprise;
import Business.Organization.TransportOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DeliveryWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class DriverWorkAreaJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final UserAccount userAccount;
    private final TransportOrganization organization;
    private final Enterprise enterprise;

    public DriverWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,
            TransportOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        enterpriseValueLabel.setText(enterprise.getName());
        userValueLabel.setText(account.getUsername());
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel m = (DefaultTableModel) deliveryJTable.getModel();
        m.setRowCount(0);
        for (WorkRequest r : userAccount.getWorkQueue().getWorkRequestList()) {
            if (!(r instanceof DeliveryWorkRequest)) continue;
            DeliveryWorkRequest d = (DeliveryWorkRequest) r;
            m.addRow(new Object[]{d, d.getPickupLocation(), d.getDropLocation(),
                d.getAssignedTruck(), d.getStatus()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        enterpriseValueLabel = new javax.swing.JLabel();
        userValueLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deliveryJTable = new javax.swing.JTable();
        loadingJButton = new javax.swing.JButton();
        unloadingJButton = new javax.swing.JButton();
        proofJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setText("Driver Portal");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, -1, -1));

        enterpriseLabel.setText("Enterprise:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 70, -1, -1));

        userLabel.setText("Driver:");
        add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 104, -1, -1));

        enterpriseValueLabel.setText("FastLane Logistics");
        add(enterpriseValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 70, -1, -1));

        userValueLabel.setText("driver");
        add(userValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 104, -1, -1));

        deliveryJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Delivery", "Pickup", "Drop", "Truck", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(deliveryJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 126, 538, 105));

        loadingJButton.setText("Mark Loaded");
        loadingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadingJButtonActionPerformed(evt);
            }
        });
        add(loadingJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 249, 120, 40));

        unloadingJButton.setText("Unloading/Inspection");
        unloadingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unloadingJButtonActionPerformed(evt);
            }
        });
        add(unloadingJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 249, -1, 40));

        proofJButton.setText("Toggle Maintenance");
        proofJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proofJButtonActionPerformed(evt);
            }
        });
        add(proofJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 249, -1, 40));

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 249, 84, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void unloadingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unloadingJButtonActionPerformed
        // TODO add your handling code here:
        int row = deliveryJTable.getSelectedRow();
        if (row < 0) return;
        DeliveryWorkRequest d = (DeliveryWorkRequest) deliveryJTable.getValueAt(row, 0);
        userProcessContainer.add("UnloadingInspectionJPanel",
                new UnloadingInspectionJPanel(userProcessContainer, d));
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_unloadingJButtonActionPerformed

    private void loadingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadingJButtonActionPerformed
        // TODO add your handling code here:
        int row = deliveryJTable.getSelectedRow();
        if (row < 0) return;
        DeliveryWorkRequest d = (DeliveryWorkRequest) deliveryJTable.getValueAt(row, 0);
        if (!DeliveryWorkRequest.STATUS_ASSIGNED.equals(d.getStatus())) {
            JOptionPane.showMessageDialog(this, "Only Assigned deliveries can be marked Loaded."); return;
        }
        d.setStatus(DeliveryWorkRequest.STATUS_LOADED);
        populateTable();
    }//GEN-LAST:event_loadingJButtonActionPerformed

    private void proofJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proofJButtonActionPerformed
        // TODO add your handling code here:
        int row = deliveryJTable.getSelectedRow();
        if (row < 0) return;
        DeliveryWorkRequest d = (DeliveryWorkRequest) deliveryJTable.getValueAt(row, 0);
        userProcessContainer.add("UpdateDeliveryProofJPanel",
                new UpdateDeliveryProofJPanel(userProcessContainer, d));
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_proofJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable deliveryJTable;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseValueLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadingJButton;
    private javax.swing.JButton proofJButton;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton unloadingJButton;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel userValueLabel;
    // End of variables declaration//GEN-END:variables
}
