/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TransportRole;

import Business.Employee.Employee;
import Business.Organization.TransportOrganization;
import Business.Role.DriverRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class ManageDriverAccountJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final TransportOrganization organization;

    public ManageDriverAccountJPanel(JPanel userProcessContainer, TransportOrganization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel m = (DefaultTableModel) driverJTable.getModel();
        m.setRowCount(0);
        for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
            if (ua.getRole() instanceof DriverRole) {
                m.addRow(new Object[]{ua.getUsername(),
                    ua.getEmployee() == null ? "" : ua.getEmployee().getName(), "Driver"});
            }
        }
        autoSizeColumns(driverJTable);
    }
    
    private void autoSizeColumns(javax.swing.JTable t) {
        t.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        for (int col = 0; col < t.getColumnCount(); col++) {
            int w = 60;
            for (int r = 0; r < t.getRowCount(); r++) {
                w = Math.max(w, t.prepareRenderer(t.getCellRenderer(r, col), r, col)
                               .getPreferredSize().width + 20);
            }
            t.getColumnModel().getColumn(col).setPreferredWidth(w);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        driverJTable = new javax.swing.JTable();
        createJButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        userJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        passLabel = new javax.swing.JLabel();
        passJTextField = new javax.swing.JPasswordField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setText("Manage Driver Account");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 27, -1, -1));

        driverJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Employee", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(driverJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 71, 538, 105));

        createJButton.setText("Create Driver");
        createJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJButtonActionPerformed(evt);
            }
        });
        add(createJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 303, -1, -1));

        nameLabel.setText("Employee Name:");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 191, -1, -1));
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 188, 256, -1));

        userLabel.setText("Username:");
        add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 225, -1, -1));

        userJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJTextFieldActionPerformed(evt);
            }
        });
        add(userJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 222, 256, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 303, -1, -1));

        passLabel.setText("Password:");
        add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 259, -1, -1));
        add(passJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 256, 256, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void userJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userJTextFieldActionPerformed

    private void createJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJButtonActionPerformed
        // TODO add your handling code here:
        String name = nameJTextField.getText().trim();
        String user = userJTextField.getText().trim();
        String pass = new String(passJTextField.getPassword());
        if (name.isEmpty() || user.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields required."); return;
        }
        if (!organization.getUserAccountDirectory().checkIfUsernameIsUnique(user)) {
            JOptionPane.showMessageDialog(this, "Username already taken."); return;
        }
        Employee emp = organization.getEmployeeDirectory().createEmployee(name);
        organization.getUserAccountDirectory().createUserAccount(user, pass, emp, new DriverRole());
        nameJTextField.setText(""); userJTextField.setText(""); passJTextField.setText("");
        populateTable();
    }//GEN-LAST:event_createJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createJButton;
    private javax.swing.JTable driverJTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField passJTextField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField userJTextField;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
