/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TransportRole;

import Business.Fleet.Truck;
import Business.Organization.TransportOrganization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class ManageFleetJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final TransportOrganization organization;

    public ManageFleetJPanel(JPanel userProcessContainer, TransportOrganization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel m = (DefaultTableModel) fleetJTable.getModel();
        m.setRowCount(0);
        for (Truck t : organization.getFleetDirectory().getTruckList()) {
            m.addRow(new Object[]{t, t.getLicensePlate(), t.getModel(),
                t.getCapacityKg(), t.getStatus()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fleetJTable = new javax.swing.JTable();
        addJButton = new javax.swing.JButton();
        removeJButton = new javax.swing.JButton();
        plateLabel = new javax.swing.JLabel();
        plateJTextField = new javax.swing.JTextField();
        toggleMaintenanceJButton = new javax.swing.JButton();
        modelLabel = new javax.swing.JLabel();
        modelJTextField = new javax.swing.JTextField();
        capacityLabel = new javax.swing.JLabel();
        capacityJTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 289, -1, -1));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setText("Manage Fleet");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 27, -1, -1));

        fleetJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Truck", "Plate", "Model", "Capacity (kg)", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(fleetJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 71, 538, 105));

        addJButton.setText("Add Truck");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 289, -1, -1));

        removeJButton.setText("Remove");
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });
        add(removeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 289, -1, -1));

        plateLabel.setText("Plate:");
        add(plateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 210, -1, -1));

        plateJTextField.setMinimumSize(new java.awt.Dimension(120, 40));
        add(plateJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 207, 100, -1));

        toggleMaintenanceJButton.setText("Toggle Maintenance");
        toggleMaintenanceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleMaintenanceJButtonActionPerformed(evt);
            }
        });
        add(toggleMaintenanceJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 289, -1, -1));

        modelLabel.setText("Model:");
        add(modelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 210, -1, -1));

        modelJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelJTextFieldActionPerformed(evt);
            }
        });
        add(modelJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 207, 110, -1));

        capacityLabel.setText("Cap kg:");
        add(capacityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 210, -1, -1));
        add(capacityJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 207, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void modelJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelJTextFieldActionPerformed

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        // TODO add your handling code here:
        try {
            String plate = plateJTextField.getText().trim();
            String model = modelJTextField.getText().trim();
            double cap = Double.parseDouble(capacityJTextField.getText().trim());
            if (plate.isEmpty() || model.isEmpty()) throw new IllegalArgumentException();
            organization.getFleetDirectory().addTruck(plate, model, cap);
            plateJTextField.setText(""); modelJTextField.setText(""); capacityJTextField.setText("");
            populateTable();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Enter valid plate, model, and numeric capacity.");
        }
    }//GEN-LAST:event_addJButtonActionPerformed

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJButtonActionPerformed
        // TODO add your handling code here:
        int row = fleetJTable.getSelectedRow();
        if (row < 0) return;
        Truck t = (Truck) fleetJTable.getValueAt(row, 0);
        if (Truck.STATUS_ASSIGNED.equals(t.getStatus())) {
            JOptionPane.showMessageDialog(this, "Cannot remove — truck is currently assigned."); return;
        }
        organization.getFleetDirectory().removeTruck(t);
        populateTable();
    }//GEN-LAST:event_removeJButtonActionPerformed

    private void toggleMaintenanceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleMaintenanceJButtonActionPerformed
        // TODO add your handling code here:
        int row = fleetJTable.getSelectedRow();
        if (row < 0) return;
        Truck t = (Truck) fleetJTable.getValueAt(row, 0);
        if (Truck.STATUS_ASSIGNED.equals(t.getStatus())) {
            JOptionPane.showMessageDialog(this, "Cannot toggle — truck is assigned to a delivery."); return;
        }
        t.setStatus(Truck.STATUS_MAINTENANCE.equals(t.getStatus())
                ? Truck.STATUS_AVAILABLE : Truck.STATUS_MAINTENANCE);
        populateTable();
    }//GEN-LAST:event_toggleMaintenanceJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField capacityJTextField;
    private javax.swing.JLabel capacityLabel;
    private javax.swing.JTable fleetJTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField modelJTextField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField plateJTextField;
    private javax.swing.JLabel plateLabel;
    private javax.swing.JButton removeJButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton toggleMaintenanceJButton;
    // End of variables declaration//GEN-END:variables
}
