/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TransportRole;

import Business.Fleet.Truck;
import Business.Organization.TransportOrganization;
import Business.WorkQueue.DeliveryWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class ReportDeliveryResultJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final TransportOrganization organization;

    public ReportDeliveryResultJPanel(JPanel userProcessContainer, TransportOrganization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel m = (DefaultTableModel) requestJTable.getModel();
        m.setRowCount(0);
        for (WorkRequest r : organization.getWorkQueue().getWorkRequestList()) {
            if (!(r instanceof DeliveryWorkRequest)) continue;
            DeliveryWorkRequest d = (DeliveryWorkRequest) r;
            if (!DeliveryWorkRequest.STATUS_COMPLETED.equals(d.getStatus())) continue;
            m.addRow(new Object[]{d, d.getAssignedDriver(), d.getInspectionResult(),
                d.getProofReference(), d.getStatus()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestJTable = new javax.swing.JTable();
        submitJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        reportLabel = new javax.swing.JLabel();
        reportJTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 259, -1, -1));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setText("Report Delivery Result");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 27, -1, -1));

        requestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request", "Driver", "Inspection", "Proof", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 71, 538, 105));

        submitJButton.setText("Submit & Close");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 207, -1, -1));

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 207, -1, -1));

        reportLabel.setText("Report:");
        add(reportLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 210, -1, -1));
        add(reportJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 207, 231, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        // TODO add your handling code here:
        int row = requestJTable.getSelectedRow();
        if (row < 0) { JOptionPane.showMessageDialog(this, "Pick a completed request."); return; }
        DeliveryWorkRequest d = (DeliveryWorkRequest) requestJTable.getValueAt(row, 0);
        d.setDeliveryReport(reportJTextField.getText());
        d.setStatus(DeliveryWorkRequest.STATUS_REPORTED);
        d.setResolveDate(new Date());
        Truck t = d.getAssignedTruck();
        if (t != null) t.setStatus(Truck.STATUS_AVAILABLE);
        populateTable();
        JOptionPane.showMessageDialog(this, "Delivery reported back to sender.");
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTextField reportJTextField;
    private javax.swing.JLabel reportLabel;
    private javax.swing.JTable requestJTable;
    private javax.swing.JButton submitJButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
