/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TransportRole;

import Business.Fleet.Truck;
import Business.Organization.TransportOrganization;
import Business.WorkQueue.DeliveryWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class SchedulingJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final TransportOrganization organization;
    private final SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    public SchedulingJPanel(JPanel userProcessContainer, TransportOrganization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        populateRequestTable();
        populateTruckCombo();
    }

    public void populateRequestTable() {
        DefaultTableModel m = (DefaultTableModel) requestJTable.getModel();
        m.setRowCount(0);
        for (WorkRequest r : organization.getWorkQueue().getWorkRequestList()) {
            if (!(r instanceof DeliveryWorkRequest)) continue;
            DeliveryWorkRequest d = (DeliveryWorkRequest) r;
            if (DeliveryWorkRequest.STATUS_COMPLETED.equals(d.getStatus())
                    || DeliveryWorkRequest.STATUS_REPORTED.equals(d.getStatus())) continue;
            m.addRow(new Object[]{d, d.getPickupLocation(), d.getDropLocation(),
                d.getScheduledDate() == null ? "" : sdf.format(d.getScheduledDate()),
                d.getAssignedTruck(), d.getStatus()});
        }
        autoSizeColumns(requestJTable);
    }
    
    private void autoSizeColumns(javax.swing.JTable t) {
        t.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        for (int col = 0; col < t.getColumnCount(); col++) {
            int w = 60;
            for (int r = 0; r < t.getRowCount(); r++) {
                w = Math.max(w, t.prepareRenderer(t.getCellRenderer(r, col), r, col)
                               .getPreferredSize().width + 20);
            }
            t.getColumnModel().getColumn(col).setPreferredWidth(w);
        }
    }

    private void populateTruckCombo() {
        truckJComboBox.removeAllItems();
        for (Truck t : organization.getFleetDirectory().getTruckList()) {
            if (Truck.STATUS_AVAILABLE.equals(t.getStatus())) truckJComboBox.addItem(t);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestJTable = new javax.swing.JTable();
        assignJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        dateLabel = new javax.swing.JLabel();
        dateJTextField = new javax.swing.JTextField();
        truckLabel = new javax.swing.JLabel();
        truckJComboBox = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 276, -1, -1));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setText("Scheduling");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 27, -1, -1));

        requestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Request", "Pickup", "Drop", "Scheduled", "Truck", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 71, 538, 105));

        assignJButton.setText("Schedule");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 276, -1, -1));

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 276, -1, -1));

        dateLabel.setText("Scheduled Date (yyyy-mm-dd):");
        add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 210, -1, -1));
        add(dateJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 207, 107, -1));

        truckLabel.setText("Assign Truck:");
        add(truckLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 210, -1, -1));

        truckJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truckJComboBoxActionPerformed(evt);
            }
        });
        add(truckJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 207, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void truckJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truckJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_truckJComboBoxActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed
        // TODO add your handling code here:
         int row = requestJTable.getSelectedRow();
        if (row < 0) { JOptionPane.showMessageDialog(this, "Pick a request first."); return; }
        Truck t = (Truck) truckJComboBox.getSelectedItem();
        if (t == null) { JOptionPane.showMessageDialog(this, "No available truck selected."); return; }
        Date scheduled;
        try { scheduled = sdf.parse(dateJTextField.getText().trim()); }
        catch (Exception ex) { JOptionPane.showMessageDialog(this, "Date must be yyyy-MM-dd"); return; }
        DeliveryWorkRequest d = (DeliveryWorkRequest) requestJTable.getValueAt(row, 0);
        d.setScheduledDate(scheduled);
        d.setAssignedTruck(t);
        d.setStatus(DeliveryWorkRequest.STATUS_ASSIGNED);
        t.setStatus(Truck.STATUS_ASSIGNED);
        populateRequestTable();
        populateTruckCombo();
        JOptionPane.showMessageDialog(this, "Scheduled and truck assigned.");
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        populateRequestTable(); populateTruckCombo();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField dateJTextField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTable requestJTable;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JComboBox<Truck> truckJComboBox;
    private javax.swing.JLabel truckLabel;
    // End of variables declaration//GEN-END:variables
}
