/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TransportRole;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.TransportOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Nakka
 */
public class TransportAdminWorkAreaJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final UserAccount userAccount;
    private final TransportOrganization organization;
    private final Enterprise enterprise;
    private final EcoSystem business;

    // ---- Edit the generated constructor to look like this ----
    public TransportAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,
            TransportOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        enterpriseValueLabel.setText(enterprise.getName());
        userValueLabel.setText(account.getUsername());
    }
    
    private void navigate(String key, JPanel panel) {
        userProcessContainer.add(key, panel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        enterpriseValueLabel = new javax.swing.JLabel();
        userValueLabel = new javax.swing.JLabel();
        receiveDeliveryJButton = new javax.swing.JButton();
        schedulingJButton = new javax.swing.JButton();
        createDeliveryJButton = new javax.swing.JButton();
        reportDeliveryResultJButton = new javax.swing.JButton();
        manageDriverAccountJButton = new javax.swing.JButton();
        manageFleetJButton = new javax.swing.JButton();
        viewDeliveryStatusJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setText("Transport Administrator Portal");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 25, -1, -1));

        enterpriseLabel.setText("Enterprise:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 89, -1, -1));

        userLabel.setText("User:");
        add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 123, -1, -1));

        enterpriseValueLabel.setText("FastLane Logistics");
        add(enterpriseValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 89, -1, -1));

        userValueLabel.setText("transadmin");
        add(userValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 123, -1, -1));

        receiveDeliveryJButton.setText("Receive Delivery Request");
        receiveDeliveryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveDeliveryJButtonActionPerformed(evt);
            }
        });
        add(receiveDeliveryJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 180, 203, 35));

        schedulingJButton.setText("Scheduling Arrangement");
        schedulingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedulingJButtonActionPerformed(evt);
            }
        });
        add(schedulingJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 180, 184, 35));

        createDeliveryJButton.setText("Create Delivery Order");
        createDeliveryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDeliveryJButtonActionPerformed(evt);
            }
        });
        add(createDeliveryJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 233, 203, 32));

        reportDeliveryResultJButton.setText("Report Delivery Result");
        reportDeliveryResultJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportDeliveryResultJButtonActionPerformed(evt);
            }
        });
        add(reportDeliveryResultJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 233, 184, 32));

        manageDriverAccountJButton.setText("Manage Driver Account");
        manageDriverAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDriverAccountJButtonActionPerformed(evt);
            }
        });
        add(manageDriverAccountJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 283, 203, 34));

        manageFleetJButton.setText("Manage Fleet");
        manageFleetJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFleetJButtonActionPerformed(evt);
            }
        });
        add(manageFleetJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 283, 184, 34));

        viewDeliveryStatusJButton.setText("View Delivery Status");
        viewDeliveryStatusJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDeliveryStatusJButtonActionPerformed(evt);
            }
        });
        add(viewDeliveryStatusJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 200, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void createDeliveryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDeliveryJButtonActionPerformed
        // TODO add your handling code here:
        navigate("CreateDeliveryOrderJPanel",
                new CreateDeliveryOrderJPanel(userProcessContainer, organization, userAccount));
    }//GEN-LAST:event_createDeliveryJButtonActionPerformed

    private void receiveDeliveryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveDeliveryJButtonActionPerformed
        // TODO add your handling code here:
        navigate("ReceiveDeliveryRequestJPanel",
                new ReceiveDeliveryRequestJPanel(userProcessContainer, organization));
    }//GEN-LAST:event_receiveDeliveryJButtonActionPerformed

    private void schedulingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedulingJButtonActionPerformed
        // TODO add your handling code here:
        navigate("SchedulingJPanel",
                new SchedulingJPanel(userProcessContainer, organization));
    }//GEN-LAST:event_schedulingJButtonActionPerformed

    private void reportDeliveryResultJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportDeliveryResultJButtonActionPerformed
        // TODO add your handling code here:
        navigate("ReportDeliveryResultJPanel",
                new ReportDeliveryResultJPanel(userProcessContainer, organization));
    }//GEN-LAST:event_reportDeliveryResultJButtonActionPerformed

    private void manageDriverAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDriverAccountJButtonActionPerformed
        // TODO add your handling code here:
        navigate("ManageDriverAccountJPanel",
                new ManageDriverAccountJPanel(userProcessContainer, organization));
    }//GEN-LAST:event_manageDriverAccountJButtonActionPerformed

    private void manageFleetJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFleetJButtonActionPerformed
        // TODO add your handling code here:
        navigate("ManageFleetJPanel",
                new ManageFleetJPanel(userProcessContainer, organization));
    }//GEN-LAST:event_manageFleetJButtonActionPerformed

    private void viewDeliveryStatusJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDeliveryStatusJButtonActionPerformed
        // TODO add your handling code here:
        navigate("ViewDeliveryStatusJPanel",
                new ViewDeliveryStatusJPanel(userProcessContainer, organization));
    }//GEN-LAST:event_viewDeliveryStatusJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createDeliveryJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseValueLabel;
    private javax.swing.JButton manageDriverAccountJButton;
    private javax.swing.JButton manageFleetJButton;
    private javax.swing.JButton receiveDeliveryJButton;
    private javax.swing.JButton reportDeliveryResultJButton;
    private javax.swing.JButton schedulingJButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel userValueLabel;
    private javax.swing.JButton viewDeliveryStatusJButton;
    // End of variables declaration//GEN-END:variables
}
