/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TransportRole;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.TransportOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Nakka
 */
public class TransportAdminWorkAreaJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final UserAccount userAccount;
    private final TransportOrganization organization;
    private final Enterprise enterprise;
    private final EcoSystem business;

    // ---- Edit the generated constructor to look like this ----
    public TransportAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,
            TransportOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        enterpriseValueLabel.setText(enterprise.getName());
        userValueLabel.setText(account.getUsername());
    }
    
    private void navigate(String key, JPanel panel) {
        userProcessContainer.add(key, panel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        enterpriseValueLabel = new javax.swing.JLabel();
        userValueLabel = new javax.swing.JLabel();
        receiveDeliveryJButton = new javax.swing.JButton();
        schedulingJButton = new javax.swing.JButton();
        createDeliveryJButton = new javax.swing.JButton();
        reportDeliveryResultJButton = new javax.swing.JButton();
        manageDriverAccountJButton = new javax.swing.JButton();
        manageFleetJButton = new javax.swing.JButton();
        viewDeliveryStatusJButton = new javax.swing.JButton();

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setText("Transport Administrator Portal");

        enterpriseLabel.setText("Enterprise:");

        userLabel.setText("User:");

        enterpriseValueLabel.setText("FastLane Logistics");

        userValueLabel.setText("transadmin");

        receiveDeliveryJButton.setText("Receive Delivery Request");
        receiveDeliveryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveDeliveryJButtonActionPerformed(evt);
            }
        });

        schedulingJButton.setText("Scheduling Arrangement");
        schedulingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedulingJButtonActionPerformed(evt);
            }
        });

        createDeliveryJButton.setText("Create Delivery Order");
        createDeliveryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDeliveryJButtonActionPerformed(evt);
            }
        });

        reportDeliveryResultJButton.setText("Report Delivery Result");
        reportDeliveryResultJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportDeliveryResultJButtonActionPerformed(evt);
            }
        });

        manageDriverAccountJButton.setText("Manage Driver Account");
        manageDriverAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDriverAccountJButtonActionPerformed(evt);
            }
        });

        manageFleetJButton.setText("Manage Fleet");
        manageFleetJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFleetJButtonActionPerformed(evt);
            }
        });

        viewDeliveryStatusJButton.setText("View Delivery Status");
        viewDeliveryStatusJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDeliveryStatusJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(titleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userLabel)
                                .addGap(18, 18, 18)
                                .addComponent(userValueLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterpriseLabel)
                                .addGap(18, 18, 18)
                                .addComponent(enterpriseValueLabel)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewDeliveryStatusJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createDeliveryJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageDriverAccountJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(receiveDeliveryJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reportDeliveryResultJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageFleetJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(schedulingJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titleLabel)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel)
                    .addComponent(enterpriseValueLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel)
                    .addComponent(userValueLabel))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(schedulingJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(receiveDeliveryJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reportDeliveryResultJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(createDeliveryJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageDriverAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageFleetJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(viewDeliveryStatusJButton)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createDeliveryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDeliveryJButtonActionPerformed
        // TODO add your handling code here:
        navigate("CreateDeliveryOrderJPanel",
                new CreateDeliveryOrderJPanel(userProcessContainer, organization, userAccount));
    }//GEN-LAST:event_createDeliveryJButtonActionPerformed

    private void receiveDeliveryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveDeliveryJButtonActionPerformed
        // TODO add your handling code here:
        navigate("ReceiveDeliveryRequestJPanel",
                new ReceiveDeliveryRequestJPanel(userProcessContainer, organization));
    }//GEN-LAST:event_receiveDeliveryJButtonActionPerformed

    private void schedulingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedulingJButtonActionPerformed
        // TODO add your handling code here:
        navigate("SchedulingJPanel",
                new SchedulingJPanel(userProcessContainer, organization));
    }//GEN-LAST:event_schedulingJButtonActionPerformed

    private void reportDeliveryResultJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportDeliveryResultJButtonActionPerformed
        // TODO add your handling code here:
        navigate("ReportDeliveryResultJPanel",
                new ReportDeliveryResultJPanel(userProcessContainer, organization));
    }//GEN-LAST:event_reportDeliveryResultJButtonActionPerformed

    private void manageDriverAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDriverAccountJButtonActionPerformed
        // TODO add your handling code here:
        navigate("ManageDriverAccountJPanel",
                new ManageDriverAccountJPanel(userProcessContainer, organization));
    }//GEN-LAST:event_manageDriverAccountJButtonActionPerformed

    private void manageFleetJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFleetJButtonActionPerformed
        // TODO add your handling code here:
        navigate("ManageFleetJPanel",
                new ManageFleetJPanel(userProcessContainer, organization));
    }//GEN-LAST:event_manageFleetJButtonActionPerformed

    private void viewDeliveryStatusJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDeliveryStatusJButtonActionPerformed
        // TODO add your handling code here:
        navigate("ViewDeliveryStatusJPanel",
                new ViewDeliveryStatusJPanel(userProcessContainer, organization));
    }//GEN-LAST:event_viewDeliveryStatusJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createDeliveryJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseValueLabel;
    private javax.swing.JButton manageDriverAccountJButton;
    private javax.swing.JButton manageFleetJButton;
    private javax.swing.JButton receiveDeliveryJButton;
    private javax.swing.JButton reportDeliveryResultJButton;
    private javax.swing.JButton schedulingJButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel userValueLabel;
    private javax.swing.JButton viewDeliveryStatusJButton;
    // End of variables declaration//GEN-END:variables
}
