/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TransportRole;

import Business.WorkQueue.DeliveryWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class UpdateDeliveryProofJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final DeliveryWorkRequest delivery;

    public UpdateDeliveryProofJPanel(JPanel userProcessContainer, DeliveryWorkRequest delivery) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.delivery = delivery;
        infoLabel.setText("Delivery to: " + delivery.getDropLocation()
                + "  (status: " + delivery.getStatus() + ")");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proofLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        submitJButton = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();
        proofJTextField = new javax.swing.JTextField();

        proofLabel.setText("Proof Reference (photo url/signature ID):");

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setText("Update Delivery Proof");

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        infoLabel.setText("Deliver to: Wholesaler (current status)");

        proofJTextField.setText("https://");
        proofJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proofJTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel)
                            .addComponent(proofLabel)
                            .addComponent(infoLabel))
                        .addContainerGap(296, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(proofJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(submitJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backJButton)))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(infoLabel)
                .addGap(18, 18, 18)
                .addComponent(proofLabel)
                .addGap(18, 18, 18)
                .addComponent(proofJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitJButton)
                    .addComponent(backJButton))
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void proofJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proofJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proofJTextFieldActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        // TODO add your handling code here:
        if (!DeliveryWorkRequest.STATUS_DELIVERED.equals(delivery.getStatus())) {
            JOptionPane.showMessageDialog(this,
                    "Proof can only be uploaded after inspection (status = Delivered)."); return;
        }
        String proof = proofJTextField.getText().trim();
        if (proof.isEmpty()) { JOptionPane.showMessageDialog(this, "Please enter a proof reference."); return; }
        delivery.setProofReference(proof);
        delivery.setStatus(DeliveryWorkRequest.STATUS_COMPLETED);
        JOptionPane.showMessageDialog(this, "Proof uploaded. Delivery marked Completed.");
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] arr = userProcessContainer.getComponents();
        Component c = arr[arr.length - 1];
        if (c instanceof DriverWorkAreaJPanel) ((DriverWorkAreaJPanel) c).populateTable();
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JTextField proofJTextField;
    private javax.swing.JLabel proofLabel;
    private javax.swing.JButton submitJButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
