/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SupplierAdminRole;

import ui.DoctorRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.SupplierOrganization;
import Business.Supplier.MaterialInventory;
import Business.Supplier.MaterialRequest;
import Business.Supplier.PickingOrder;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManageMaterialRequest extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private SupplierOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public ManageMaterialRequest(JPanel userProcessContainer, UserAccount account, SupplierOrganization organization, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        
        tblMaterialRequest.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
        tblMaterialRequest.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        
        
        populateMaterialRequestTable();
        populatePickingOrderTable();
    }
    
    public void populateMaterialRequestTable(){
        DefaultTableModel model = (DefaultTableModel) tblMaterialRequest.getModel();
        
        model.setRowCount(0);
        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()){
            
            if(wr instanceof MaterialRequest){
            
            SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, yyyy");
            MaterialRequest mr = (MaterialRequest)wr;
            MaterialInventory mi = organization.getMaterialInventoryDirectory()
                    .findInventoryByMaterial(mr.getMaterial()); mi.getAvailableQty();
                    
            Object[] row = new Object[7];
            row[0] = mr;
            row[1] = mr.getMaterial().getMaterialName();
            row[2] = mr.getQty();
            row[3] = mi.getAvailableQty();
            row[4] = mi.getPickingQty();
            row[5] = sdf.format(mr.getRequestDate());
            row[6] = mr.getStatus();
            
            model.addRow(row);
        }
    }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaterialRequest = new javax.swing.JTable();
        btnCreatePickOrder = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        enterpriseLabel = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPickingOrder = new javax.swing.JTable();
        lblMaterialRequest = new javax.swing.JLabel();
        lblPickingOrder = new javax.swing.JLabel();

        tblMaterialRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Material ID", "Material", "Request Qty", "Available Qty", "Picking Qty", "Request Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMaterialRequest);
        if (tblMaterialRequest.getColumnModel().getColumnCount() > 0) {
            tblMaterialRequest.getColumnModel().getColumn(0).setResizable(false);
            tblMaterialRequest.getColumnModel().getColumn(1).setResizable(false);
            tblMaterialRequest.getColumnModel().getColumn(2).setResizable(false);
            tblMaterialRequest.getColumnModel().getColumn(2).setHeaderValue("Request Qty");
            tblMaterialRequest.getColumnModel().getColumn(3).setResizable(false);
            tblMaterialRequest.getColumnModel().getColumn(3).setHeaderValue("Available Qty");
            tblMaterialRequest.getColumnModel().getColumn(4).setResizable(false);
            tblMaterialRequest.getColumnModel().getColumn(5).setResizable(false);
            tblMaterialRequest.getColumnModel().getColumn(6).setResizable(false);
        }

        btnCreatePickOrder.setText("Create Picking Order");
        btnCreatePickOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePickOrderActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        enterpriseLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseLabel.setText("Manage Material Request");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblPickingOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Picking Order ID", "Material ID", "Material", "Request Qty", "Picking Qty", "Request Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPickingOrder);
        if (tblPickingOrder.getColumnModel().getColumnCount() > 0) {
            tblPickingOrder.getColumnModel().getColumn(0).setResizable(false);
            tblPickingOrder.getColumnModel().getColumn(1).setResizable(false);
            tblPickingOrder.getColumnModel().getColumn(2).setResizable(false);
            tblPickingOrder.getColumnModel().getColumn(3).setResizable(false);
            tblPickingOrder.getColumnModel().getColumn(4).setResizable(false);
            tblPickingOrder.getColumnModel().getColumn(5).setResizable(false);
            tblPickingOrder.getColumnModel().getColumn(6).setResizable(false);
        }

        lblMaterialRequest.setText("Material Request");

        lblPickingOrder.setText("Picking Order");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreatePickOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack)
                            .addComponent(lblMaterialRequest)
                            .addComponent(lblPickingOrder))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblMaterialRequest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCreatePickOrder)
                .addGap(29, 29, 29)
                .addComponent(lblPickingOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnBack)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePickOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePickOrderActionPerformed
        
       int selectedRow = tblMaterialRequest.getSelectedRow();
        
        if(selectedRow <0){
            JOptionPane.showMessageDialog(null,"Please select a request","Warning",
    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        MaterialRequest mr = (MaterialRequest) tblMaterialRequest.getValueAt(selectedRow,0);
       
        MaterialInventory mi = organization.getMaterialInventoryDirectory()
                    .findInventoryByMaterial(mr.getMaterial()); 
        
        if(mr.getQty()>mi.getAvailableQty()){
             JOptionPane.showMessageDialog(null,"Available stock is insufficient","Warning",
    JOptionPane.WARNING_MESSAGE);
             return;
        }
        
        if(mr.getStatus().equals("Sent")){
        
        int currentQty = mi.getAvailableQty();
        mi.setAvailableQty(currentQty - mr.getQty());
        mi.setPickingQty(mi.getPickingQty() + mr.getQty());
        
        PickingOrder po = this.organization.getPickingOrderDirectory().addPickingOrder(mr, organization);

        mr.setStatus("Allocated");
        
        organization.getWorkQueue().getWorkRequestList().add(po);
        
        JOptionPane.showMessageDialog(null,"Create Picking Order successfully");
 
        populateMaterialRequestTable();
        populatePickingOrderTable();
        
        } else{
            JOptionPane.showMessageDialog(null,"This request has already been processed.","Warning",
    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
    }//GEN-LAST:event_btnCreatePickOrderActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreatePickOrder;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMaterialRequest;
    private javax.swing.JLabel lblPickingOrder;
    private javax.swing.JTable tblMaterialRequest;
    private javax.swing.JTable tblPickingOrder;
    // End of variables declaration//GEN-END:variables

    private void populatePickingOrderTable() {
       DefaultTableModel model = (DefaultTableModel) tblPickingOrder.getModel();
        
        model.setRowCount(0);
        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()){
            
            if(wr instanceof PickingOrder){
            
            SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, yyyy");
            PickingOrder po = (PickingOrder)wr;
                     
            Object[] row = new Object[7];
            row[0] = po;
            row[1] = po.getMaterialRequest().getMaterial();
            row[2] = po.getMaterialRequest().getMaterial().getMaterialName();
            row[3] = po.getMaterialRequest().getQty();
            row[4] = po.getMaterialRequest().getQty();
            row[5] = sdf.format(po.getRequestDate());
            row[6] = po.getStatus();
            
            model.addRow(row);
        }
    }
    
    }
}
