/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.ProcurementRole;

import ui.PharmacyRole.*;
import ui.SupplierAdminRole.*;
import ui.DoctorRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.WholesalerEnterprise;
import Business.Hospital.MedicineInventory;
import Business.Hospital.ProcurementRequest;
import Business.Hospital.ReplenishmentRequest;
import Business.Organization.DoctorOrganization;
import Business.Organization.InventoryOrganization;
import Business.Organization.Organization;
import Business.Organization.PharmacyOrganization;
import Business.Organization.ProcurementOrganization;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManageProcurementRequest extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PharmacyOrganization organization;
    private ProcurementOrganization procurementOrg;
    
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public ManageProcurementRequest(JPanel userProcessContainer, UserAccount account, PharmacyOrganization organization, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        
        for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(o instanceof ProcurementOrganization){
            procurementOrg = (ProcurementOrganization)o;
            }
        }
          
        populateReplenishmentRequestTable();
        populateProcurementRequestTable();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        enterpriseLabel = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReplenishmentRequest = new javax.swing.JTable();
        lblPickingOrder = new javax.swing.JLabel();
        btnCreateProcurementRequest = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProcurementRequest = new javax.swing.JTable();
        lblPickingOrder1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        enterpriseLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseLabel.setText("Manage Procurement Request");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblReplenishmentRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Replenish ID", "Medicine ID", "Medicine", "Request Qty", "Request Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblReplenishmentRequest);
        if (tblReplenishmentRequest.getColumnModel().getColumnCount() > 0) {
            tblReplenishmentRequest.getColumnModel().getColumn(0).setResizable(false);
            tblReplenishmentRequest.getColumnModel().getColumn(1).setResizable(false);
            tblReplenishmentRequest.getColumnModel().getColumn(2).setResizable(false);
            tblReplenishmentRequest.getColumnModel().getColumn(3).setResizable(false);
            tblReplenishmentRequest.getColumnModel().getColumn(4).setResizable(false);
            tblReplenishmentRequest.getColumnModel().getColumn(5).setResizable(false);
        }

        lblPickingOrder.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblPickingOrder.setText("Replenishment Request");

        btnCreateProcurementRequest.setText("Create Procurement Request");
        btnCreateProcurementRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateProcurementRequestActionPerformed(evt);
            }
        });

        tblProcurementRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Procurement ID", "Medicine ID", "Medicine", "Request Qty", "Request Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblProcurementRequest);
        if (tblProcurementRequest.getColumnModel().getColumnCount() > 0) {
            tblProcurementRequest.getColumnModel().getColumn(0).setResizable(false);
            tblProcurementRequest.getColumnModel().getColumn(1).setResizable(false);
            tblProcurementRequest.getColumnModel().getColumn(2).setResizable(false);
            tblProcurementRequest.getColumnModel().getColumn(3).setResizable(false);
            tblProcurementRequest.getColumnModel().getColumn(4).setResizable(false);
            tblProcurementRequest.getColumnModel().getColumn(5).setResizable(false);
        }

        lblPickingOrder1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblPickingOrder1.setText("Procurement Request");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateProcurementRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPickingOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPickingOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPickingOrder)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateProcurementRequest)
                .addGap(33, 33, 33)
                .addComponent(lblPickingOrder1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnBack)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateProcurementRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateProcurementRequestActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblReplenishmentRequest.getSelectedRow();
        
        if(selectedRow <0){
            JOptionPane.showMessageDialog(null,"Please select a request","Warning",
    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ReplenishmentRequest rr = (ReplenishmentRequest) tblReplenishmentRequest.getValueAt(selectedRow,0);
        
        if(!"Requested".equals(rr.getStatus())){
            JOptionPane.showMessageDialog(null,"Procurement request has been created already.","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        } 
           
        ProcurementRequest pr = new ProcurementRequest();
        pr.setReplenishmentRequest(rr);
        
        pr.setMedicine(rr.getMedicine());
        pr.setRequestQty(rr.getReplenishQty());
        pr.setStatus("Procured");
        pr.setSender(userAccount);
        rr.setStatus("Procured");
         
        procurementOrg.getWorkQueue().getWorkRequestList().add(pr);
        
        HospitalEnterprise hospitalEnterprise = (HospitalEnterprise) enterprise;
        WholesalerEnterprise wholesaler = hospitalEnterprise.getAssignedWholesaler();

        for (Organization org : wholesaler.getOrganizationDirectory().getOrganizationList()) {

            if (org instanceof InventoryOrganization) {

                InventoryOrganization inventoryOrg = (InventoryOrganization) org;

                inventoryOrg.getWorkQueue()
                    .getWorkRequestList()
                    .add(pr);

                break;
            }
        }
        JOptionPane.showMessageDialog(null,"Procurement request has been created successfully.");
        
        populateReplenishmentRequestTable();
        populateProcurementRequestTable();
        
    }//GEN-LAST:event_btnCreateProcurementRequestActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateProcurementRequest;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblPickingOrder;
    private javax.swing.JLabel lblPickingOrder1;
    private javax.swing.JTable tblProcurementRequest;
    private javax.swing.JTable tblReplenishmentRequest;
    // End of variables declaration//GEN-END:variables

    private void populateReplenishmentRequestTable() {
       DefaultTableModel model = (DefaultTableModel) tblReplenishmentRequest.getModel();
        
        model.setRowCount(0);
        
        
        for (WorkRequest wr : procurementOrg.getWorkQueue().getWorkRequestList()){
            
            if(wr instanceof ReplenishmentRequest rr){
            
                if(rr.getStatus().equals("Requested")){
                    
                
                    SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, yyyy");
                     
                    Object[] row = new Object[6];
                    row[0] = rr;
                    row[1] = rr.getMedicine().getMedicineId();
                    row[2] = rr.getMedicine().getMedicineName();
                    row[3] = rr.getReplenishQty();
                    row[4] = sdf.format(rr.getRequestDate());
                    row[5] = rr.getStatus();
            
                    model.addRow(row);
                }
            }       
        }
    }

    private void populateProcurementRequestTable() {
         DefaultTableModel model = (DefaultTableModel) tblProcurementRequest.getModel();
        
        model.setRowCount(0);
        
        
        for (WorkRequest wr : procurementOrg.getWorkQueue().getWorkRequestList()){
            
            if(wr instanceof ProcurementRequest pr){
            
            SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, yyyy");
                     
            Object[] row = new Object[6];
            row[0] = pr;
            row[1] = pr.getMedicine().getMedicineId();
            row[2] = pr.getMedicine().getMedicineName();
            row[3] = pr.getRequestQty();
            row[4] = sdf.format(pr.getRequestDate());
            row[5] = pr.getStatus();
            
            model.addRow(row);
            }
        }
    
    }
}
