/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package ui.ProductionAdminRole;

import Business.Enterprise.SupplierEnterprise;
import Business.WorkQueue.WorkRequest;
import Business.EcoSystem;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.SupplierOrganization;
import Business.Role.SupplierAdminRole;
import Business.Supplier.Material;
import Business.Supplier.MaterialRequest;
import Business.Enterprise.Enterprise;
import Business.Organization.ProductionOrganization;
import Business.UserAccount.UserAccount;
import Business.Production.ProductionOrder;
import Business.Production.ProductionPlan;
import Business.Role.ProductionAdminRole;
import Business.Role.ProductionRole;
import Business.Role.QualityAssuranceRole;
import Business.Role.Role;
import Business.Organization.QualityAssuranceOrganization;
import Business.Employee.Employee;
import Business.Supplier.MaterialInventory;
import javax.swing.JPanel;

/**
 *
 * @author vyngo
 */
public class ProductionAdminWorkAreaJPanel extends javax.swing.JPanel {

    /** Creates new form ProductionAdminWorkAreaJPanel */
private JPanel userProcessContainer;
private UserAccount account;
private ProductionOrganization organization;
private Enterprise enterprise;

public ProductionAdminWorkAreaJPanel(JPanel userProcessContainer,
                        UserAccount account,
                        ProductionOrganization organization,
                        Enterprise enterprise) {
    initComponents();
    this.userProcessContainer = userProcessContainer;
    this.account = account;
    this.organization = organization;
    this.enterprise = enterprise;
}
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createProductionPlanButton = new javax.swing.JButton();
        checkRawMaterialStockButton = new javax.swing.JButton();
        createMaterialRequestButton = new javax.swing.JButton();
        issueProductionOrderButton = new javax.swing.JButton();
        issueDeliveryRequestButton = new javax.swing.JButton();
        manageOperatorAccountButton = new javax.swing.JButton();
        manageAdminAccountButton = new javax.swing.JButton();
        viewOrderStatusButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();

        createProductionPlanButton.setText("Create Production Plan");
        createProductionPlanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProductionPlanButtonActionPerformed(evt);
            }
        });

        checkRawMaterialStockButton.setText("Check Raw Material Stock");
        checkRawMaterialStockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRawMaterialStockButtonActionPerformed(evt);
            }
        });

        createMaterialRequestButton.setText("Create Material Request");
        createMaterialRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMaterialRequestButtonActionPerformed(evt);
            }
        });

        issueProductionOrderButton.setText("Issue Production Order");
        issueProductionOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueProductionOrderButtonActionPerformed(evt);
            }
        });

        issueDeliveryRequestButton.setText("Issue Delivery Request");
        issueDeliveryRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueDeliveryRequestButtonActionPerformed(evt);
            }
        });

        manageOperatorAccountButton.setText("Manage Operator & QA Account");
        manageOperatorAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOperatorAccountButtonActionPerformed(evt);
            }
        });

        manageAdminAccountButton.setText("Manage Admin Account");
        manageAdminAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdminAccountButtonActionPerformed(evt);
            }
        });

        viewOrderStatusButton.setText("View Order Status");
        viewOrderStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderStatusButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        titleLabel.setText("Production Administrator Portal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkRawMaterialStockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createProductionPlanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createMaterialRequestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(issueProductionOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageOperatorAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(issueDeliveryRequestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageAdminAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewOrderStatusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(titleLabel)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titleLabel)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createProductionPlanButton)
                    .addComponent(issueDeliveryRequestButton))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkRawMaterialStockButton)
                    .addComponent(manageOperatorAccountButton))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createMaterialRequestButton)
                    .addComponent(manageAdminAccountButton))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issueProductionOrderButton)
                    .addComponent(viewOrderStatusButton))
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkRawMaterialStockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRawMaterialStockButtonActionPerformed
        // TODO add your handling code here:
    java.util.ArrayList<MaterialInventory> inventoryList = organization.getRawMaterialInventoryDirectory().getInventoryList();
    if (inventoryList.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No raw material in stock yet.");
        return;
    }
    StringBuilder sb = new StringBuilder();
    for (MaterialInventory mi : inventoryList) {
        sb.append(mi.getMaterial().getMaterialName())
          .append(" - Available: ").append(mi.getAvailableQty())
          .append("\n");
    }
    javax.swing.JOptionPane.showMessageDialog(this, sb.toString(), "Raw Material Stock", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_checkRawMaterialStockButtonActionPerformed

    private void createProductionPlanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProductionPlanButtonActionPerformed
        // TODO add your handling code here:
        String productName = javax.swing.JOptionPane.showInputDialog(this, "Enter product name:");
        if (productName == null || productName.trim().isEmpty()) {
            return;
        }
        String qtyStr = javax.swing.JOptionPane.showInputDialog(this, "Enter planned quantity:");
        if (qtyStr == null || qtyStr.trim().isEmpty()) {
            return;
        }
        int qty;
        try {
            qty = Integer.parseInt(qtyStr.trim());
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Quantity must be a number.");
            return;
        }
        if (qty <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Quantity must be greater than 0.");
            return;
        }

        ProductionPlan plan = organization.getProductionPlanDirectory().addProductionPlan(productName, qty);

        javax.swing.JOptionPane.showMessageDialog(this, "Production plan created: " + plan.getPlanId() + " - " + productName + " (" + qty + ")");

    }//GEN-LAST:event_createProductionPlanButtonActionPerformed

    private void createMaterialRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMaterialRequestButtonActionPerformed
        // TODO add your handling code here:
    EcoSystem system = EcoSystem.getInstance();

    Enterprise supplierEnterprise = null;
    outer:
    for (Network network : system.getNetworkList()) {
        for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (ent.getEnterpriseType() == Enterprise.EnterpriseType.Supplier) {
                supplierEnterprise = ent;
                break outer;
            }
        }
    }
    if (supplierEnterprise == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No Supplier enterprise found.");
        return;
    }

    SupplierOrganization supplierOrg = null;
    for (Organization org : supplierEnterprise.getOrganizationDirectory().getOrganizationList()) {
        if (org instanceof SupplierOrganization) {
            supplierOrg = (SupplierOrganization) org;
            break;
        }
    }
    if (supplierOrg == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No Supplier organization found.");
        return;
    }

    UserAccount supplierAdminAccount = null;
    for (UserAccount ua : supplierOrg.getUserAccountDirectory().getUserAccountList()) {
        if (ua.getRole() instanceof SupplierAdminRole) {
            supplierAdminAccount = ua;
            break;
        }
    }
    if (supplierAdminAccount == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No Supplier Admin account found.");
        return;
    }

    java.util.ArrayList<Material> materials = ((SupplierEnterprise) supplierEnterprise).getMaterialCatalog().getMaterialList();
    if (materials.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No materials available in Supplier catalog.");
        return;
    }
    String[] materialNames = new String[materials.size()];
    for (int i = 0; i < materials.size(); i++) {
        materialNames[i] = materials.get(i).getMaterialName();
    }
    String selectedName = (String) javax.swing.JOptionPane.showInputDialog(
            this,
            "Select material:",
            "Create Material Request",
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            materialNames,
            materialNames[0]);
    if (selectedName == null) {
        return;
    }
    Material selectedMaterial = null;
    for (Material m : materials) {
        if (m.getMaterialName().equals(selectedName)) {
            selectedMaterial = m;
            break;
        }
    }

    String qtyStr = javax.swing.JOptionPane.showInputDialog(this, "Enter quantity:");
    if (qtyStr == null || qtyStr.trim().isEmpty()) {
        return;
    }
    int qty;
    try {
        qty = Integer.parseInt(qtyStr.trim());
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Quantity must be a number.");
        return;
    }
    if (qty <= 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Quantity must be greater than 0.");
        return;
    }

    MaterialRequest mr = new MaterialRequest(selectedMaterial, qty);
    mr.setMessage("Request: " + selectedMaterial.getMaterialName());
    mr.setSender(account);
    mr.setReceiver(supplierAdminAccount);
    // MaterialRequest's own constructor defaults status to lowercase "sent",
    // but Supplier's ManageMaterialRequest screen checks for "Sent" (capital S)
    // before it will create a Picking Order. Force it here so the request
    // is actually processable on the Supplier side.
    mr.setStatus("Sent");
    supplierOrg.getWorkQueue().getWorkRequestList().add(mr);
    // Also keep a reference in Production's own queue (same object) so this
    // request shows up under Production Admin's "View Order Status" too.
    organization.getWorkQueue().getWorkRequestList().add(mr);

    javax.swing.JOptionPane.showMessageDialog(this, "Material request sent for " + selectedMaterial.getMaterialName());

    }//GEN-LAST:event_createMaterialRequestButtonActionPerformed

    private void issueProductionOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueProductionOrderButtonActionPerformed
        // TODO add your handling code here:
        java.util.ArrayList<ProductionPlan> openPlans = new java.util.ArrayList<>();
        for (ProductionPlan p : organization.getProductionPlanDirectory().getProductionPlanList()) {
            if ("Created".equals(p.getStatus())) {
                openPlans.add(p);
            }
        }
        if (openPlans.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No open production plan found. Please create a production plan first.");
            return;
        }
        String[] planLabels = new String[openPlans.size()];
        for (int i = 0; i < openPlans.size(); i++) {
            planLabels[i] = openPlans.get(i).toString();
        }
        String selectedPlanLabel = (String) javax.swing.JOptionPane.showInputDialog(
                this,
                "Select production plan:",
                "Issue Production Order",
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                planLabels,
                planLabels[0]);
        if (selectedPlanLabel == null) {
            return;
        }
        ProductionPlan selectedPlan = null;
        for (ProductionPlan p : openPlans) {
            if (p.toString().equals(selectedPlanLabel)) {
                selectedPlan = p;
                break;
            }
        }

        java.util.ArrayList<MaterialInventory> stock = organization.getRawMaterialInventoryDirectory().getInventoryList();
        if (stock.isEmpty()) {
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                    "Raw material stock is currently empty. Issue this production order anyway?",
                    "Low Stock Warning",
                    javax.swing.JOptionPane.YES_NO_OPTION);
            if (confirm != javax.swing.JOptionPane.YES_OPTION) {
                return;
            }
        }

        java.util.ArrayList<UserAccount> operators = new java.util.ArrayList<>();
        for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
            if (ua.getRole() instanceof ProductionRole) {
                operators.add(ua);
            }
        }
        if (operators.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No Production Operator account found.");
            return;
        }
        UserAccount operatorAccount;
        if (operators.size() == 1) {
            operatorAccount = operators.get(0);
        } else {
            String[] operatorNames = new String[operators.size()];
            for (int i = 0; i < operators.size(); i++) {
                operatorNames[i] = operators.get(i).getUsername();
            }
            String selectedOperatorName = (String) javax.swing.JOptionPane.showInputDialog(
                    this,
                    "Select production operator:",
                    "Issue Production Order",
                    javax.swing.JOptionPane.QUESTION_MESSAGE,
                    null,
                    operatorNames,
                    operatorNames[0]);
            if (selectedOperatorName == null) {
                return;
            }
            operatorAccount = null;
            for (UserAccount ua : operators) {
                if (ua.getUsername().equals(selectedOperatorName)) {
                    operatorAccount = ua;
                    break;
                }
            }
        }

        ProductionOrder po = new ProductionOrder(selectedPlan.getProductName(), selectedPlan.getQty());
        po.setPlanId(selectedPlan.getPlanId());
        po.setMessage("Production order: " + selectedPlan.getProductName());
        po.setSender(account);
        po.setReceiver(operatorAccount);
        organization.getWorkQueue().getWorkRequestList().add(po);

        selectedPlan.setStatus("Ordered");

        javax.swing.JOptionPane.showMessageDialog(this, "Production order issued for " + selectedPlan.getProductName()
                + " (Plan " + selectedPlan.getPlanId() + ")");

    }//GEN-LAST:event_issueProductionOrderButtonActionPerformed

    private void issueDeliveryRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueDeliveryRequestButtonActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "TODO: Issue Delivery Request screen");
        
    }//GEN-LAST:event_issueDeliveryRequestButtonActionPerformed

    private void manageOperatorAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOperatorAccountButtonActionPerformed
        // TODO add your handling code here:
    String[] roleOptions = {"Production Operator", "Quality Assurance"};
    String selectedRoleOption = (String) javax.swing.JOptionPane.showInputDialog(
            this,
            "Select account type to manage:",
            "Manage Operator & QA Account",
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            roleOptions,
            roleOptions[0]);
    if (selectedRoleOption == null) {
        return;
    }

    if (roleOptions[0].equals(selectedRoleOption)) {
        manageAccount(organization, new ProductionRole(), "Production Operator");
    } else {
        QualityAssuranceOrganization qaOrg = null;
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof QualityAssuranceOrganization) {
                qaOrg = (QualityAssuranceOrganization) org;
                break;
            }
        }
        if (qaOrg == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No Quality Assurance organization found.");
            return;
        }
        manageAccount(qaOrg, new QualityAssuranceRole(), "Quality Assurance");
    }
    }//GEN-LAST:event_manageOperatorAccountButtonActionPerformed

    private void manageAdminAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdminAccountButtonActionPerformed
        // TODO add your handling code here:
    manageAccount(organization, new ProductionAdminRole(), "Production Admin");
    }//GEN-LAST:event_manageAdminAccountButtonActionPerformed

    /**
     * Shared helper for Manage Admin Account / Manage Operator & QA Account:
     * lists existing accounts of the given role type on the given
     * organization, then optionally creates a new one.
     */
    private void manageAccount(Organization org, Role newRole, String roleLabel) {
        java.util.ArrayList<UserAccount> accounts = new java.util.ArrayList<>();
        for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
            if (ua.getRole().getClass() == newRole.getClass()) {
                accounts.add(ua);
            }
        }
        StringBuilder sb = new StringBuilder("Current " + roleLabel + " accounts:\n");
        if (accounts.isEmpty()) {
            sb.append("(none)\n");
        } else {
            for (UserAccount ua : accounts) {
                sb.append("- ").append(ua.getUsername()).append("\n");
            }
        }

        int choice = javax.swing.JOptionPane.showConfirmDialog(this,
                sb.toString() + "\nCreate a new " + roleLabel + " account?",
                "Manage Account",
                javax.swing.JOptionPane.YES_NO_OPTION);
        if (choice != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        String username = javax.swing.JOptionPane.showInputDialog(this, "Enter username:");
        if (username == null || username.trim().isEmpty()) {
            return;
        }
        if (!org.getUserAccountDirectory().checkIfUsernameIsUnique(username.trim())) {
            javax.swing.JOptionPane.showMessageDialog(this, "Username already exists.");
            return;
        }
        String password = javax.swing.JOptionPane.showInputDialog(this, "Enter password:");
        if (password == null || password.trim().isEmpty()) {
            return;
        }
        String employeeName = javax.swing.JOptionPane.showInputDialog(this, "Enter employee full name:");
        if (employeeName == null || employeeName.trim().isEmpty()) {
            return;
        }

        Employee employee = org.getEmployeeDirectory().createEmployee(employeeName.trim());
        org.getUserAccountDirectory().createUserAccount(username.trim(), password.trim(), employee, newRole);

        javax.swing.JOptionPane.showMessageDialog(this, roleLabel + " account created: " + username.trim());
    }

    private void viewOrderStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderStatusButtonActionPerformed
        // TODO add your handling code here
    java.util.ArrayList<WorkRequest> requests = organization.getWorkQueue().getWorkRequestList();
    if (requests.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No requests in the queue.");
        return;
    }
    StringBuilder sb = new StringBuilder();
    for (WorkRequest wr : requests) {
        sb.append(wr.toString()).append(" - ").append(wr.getStatus()).append("\n");
    }
    javax.swing.JOptionPane.showMessageDialog(this, sb.toString(), "Order Status", javax.swing.JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_viewOrderStatusButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkRawMaterialStockButton;
    private javax.swing.JButton createMaterialRequestButton;
    private javax.swing.JButton createProductionPlanButton;
    private javax.swing.JButton issueDeliveryRequestButton;
    private javax.swing.JButton issueProductionOrderButton;
    private javax.swing.JButton manageAdminAccountButton;
    private javax.swing.JButton manageOperatorAccountButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewOrderStatusButton;
    // End of variables declaration//GEN-END:variables

}
