/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package ui.ProductionAdminRole;

import Business.Enterprise.Enterprise;
import Business.Organization.ProductionOrganization;
import Business.UserAccount.UserAccount;
import Business.Production.ProductionOrder;
import Business.Role.ProductionRole;
import javax.swing.JPanel;

/**
 *
 * @author vyngo
 */
public class ProductionAdminWorkAreaJPanel extends javax.swing.JPanel {

    /** Creates new form ProductionAdminWorkAreaJPanel */
private JPanel userProcessContainer;
private UserAccount account;
private ProductionOrganization organization;
private Enterprise enterprise;

public ProductionAdminWorkAreaJPanel(JPanel userProcessContainer,
                        UserAccount account,
                        ProductionOrganization organization,
                        Enterprise enterprise) {
    initComponents();
    this.userProcessContainer = userProcessContainer;
    this.account = account;
    this.organization = organization;
    this.enterprise = enterprise;
}
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createProductionPlanButton = new javax.swing.JButton();
        checkRawMaterialStockButton = new javax.swing.JButton();
        createMaterialRequestButton = new javax.swing.JButton();
        issueProductionOrderButton = new javax.swing.JButton();
        issueDeliveryRequestButton = new javax.swing.JButton();
        manageOperatorAccountButton = new javax.swing.JButton();
        manageAdminAccountButton = new javax.swing.JButton();
        viewOrderStatusButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();

        createProductionPlanButton.setText("Create Production Plan");
        createProductionPlanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProductionPlanButtonActionPerformed(evt);
            }
        });

        checkRawMaterialStockButton.setText("Check Raw Material Stock");
        checkRawMaterialStockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRawMaterialStockButtonActionPerformed(evt);
            }
        });

        createMaterialRequestButton.setText("Create Material Request");
        createMaterialRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMaterialRequestButtonActionPerformed(evt);
            }
        });

        issueProductionOrderButton.setText("Issue Production Order");
        issueProductionOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueProductionOrderButtonActionPerformed(evt);
            }
        });

        issueDeliveryRequestButton.setText("Issue Delivery Request");
        issueDeliveryRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueDeliveryRequestButtonActionPerformed(evt);
            }
        });

        manageOperatorAccountButton.setText("Manage Operator & QA Account");
        manageOperatorAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOperatorAccountButtonActionPerformed(evt);
            }
        });

        manageAdminAccountButton.setText("Manage Admin Account");
        manageAdminAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdminAccountButtonActionPerformed(evt);
            }
        });

        viewOrderStatusButton.setText("View Order Status");
        viewOrderStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderStatusButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        titleLabel.setText("Production Administrator Portal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkRawMaterialStockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createProductionPlanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createMaterialRequestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(issueProductionOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageOperatorAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(issueDeliveryRequestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageAdminAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewOrderStatusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(titleLabel)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titleLabel)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createProductionPlanButton)
                    .addComponent(issueDeliveryRequestButton))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkRawMaterialStockButton)
                    .addComponent(manageOperatorAccountButton))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createMaterialRequestButton)
                    .addComponent(manageAdminAccountButton))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issueProductionOrderButton)
                    .addComponent(viewOrderStatusButton))
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkRawMaterialStockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRawMaterialStockButtonActionPerformed
        // TODO add your handling code here:
       javax.swing.JOptionPane.showMessageDialog(this, "TODO: Check Raw Material Stock screen");
    }//GEN-LAST:event_checkRawMaterialStockButtonActionPerformed

    private void createProductionPlanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProductionPlanButtonActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "TODO: Create Production Plan screen");
    
    }//GEN-LAST:event_createProductionPlanButtonActionPerformed

    private void createMaterialRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMaterialRequestButtonActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "TODO: Create Material Request screen");
    }//GEN-LAST:event_createMaterialRequestButtonActionPerformed

    private void issueProductionOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueProductionOrderButtonActionPerformed
        // TODO add your handling code here:
        String productName = javax.swing.JOptionPane.showInputDialog(this, "Enter product name:");
        if (productName == null || productName.trim().isEmpty()) {
            return;
        }
        String qtyStr = javax.swing.JOptionPane.showInputDialog(this, "Enter quantity:");
        if (qtyStr == null || qtyStr.trim().isEmpty()) {
            return;
        }
        int qty;
        try {
            qty = Integer.parseInt(qtyStr.trim());
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Quantity must be a number.");
            return;
        }

        UserAccount operatorAccount = null;
        for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
            if (ua.getRole() instanceof ProductionRole) {
                operatorAccount = ua;
                break;
            }
        }
        if (operatorAccount == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No Production Operator account found.");
            return;
        }

        ProductionOrder po = new ProductionOrder(productName, qty);
        po.setMessage("Production order: " + productName);
        po.setSender(account);
        po.setReceiver(operatorAccount);
        organization.getWorkQueue().getWorkRequestList().add(po);

        javax.swing.JOptionPane.showMessageDialog(this, "Production order issued for " + productName);
    
    }//GEN-LAST:event_issueProductionOrderButtonActionPerformed

    private void issueDeliveryRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueDeliveryRequestButtonActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "TODO: Issue Delivery Request screen");
        
    }//GEN-LAST:event_issueDeliveryRequestButtonActionPerformed

    private void manageOperatorAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOperatorAccountButtonActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "TODO: Manage Operator & QA Account screen");
    }//GEN-LAST:event_manageOperatorAccountButtonActionPerformed

    private void manageAdminAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdminAccountButtonActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "TODO: Manage Admin Account screen");
    }//GEN-LAST:event_manageAdminAccountButtonActionPerformed

    private void viewOrderStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderStatusButtonActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "TODO: View Order Status screen");
    }//GEN-LAST:event_viewOrderStatusButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkRawMaterialStockButton;
    private javax.swing.JButton createMaterialRequestButton;
    private javax.swing.JButton createProductionPlanButton;
    private javax.swing.JButton issueDeliveryRequestButton;
    private javax.swing.JButton issueProductionOrderButton;
    private javax.swing.JButton manageAdminAccountButton;
    private javax.swing.JButton manageOperatorAccountButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewOrderStatusButton;
    // End of variables declaration//GEN-END:variables

}
